### ISSUE TITLE
aws_security_group out of sync

### ISSUE THREAD

**Issue by john-casey** [chef/chef-provisioning-aws#121]
There is no way to recover from the situation where security group that is provisioned using aws_security_group, then it later gets deleted on the AWS console. If you run the recipe to converge, it complains about that the AWS key is not found.
```
    - create elastichef-dev-key on aws from local key at elastichef-dev-key.pem
  * aws_security_group[elastichef-app-sg] action create[2015-03-04T07:18:09-05:00] INFO: Processing aws_security_group[elastichef-app-sg] action create (elastichef::create line 56)

    
    ================================================================================
    Error executing action `create` on resource 'aws_security_group[elastichef-app-sg]'
    ================================================================================
    
    AWS::EC2::Errors::InvalidGroup::NotFound
    ----------------------------------------
    The security group 'sg-a1d408cc' does not exist
    
    Resource Declaration:
    ---------------------
    # In /home/john/.chef/local-mode-cache/cache/cookbooks/elastichef/recipes/create.rb
    
     56: aws_security_group "#{application}-app-sg" do
     57:   description "#{application} app servers" 
     58:   inbound_rules [
     59:     {:ports =>   22, :protocol => :tcp, :sources => ['0.0.0.0/0'] },
     60:     {:ports =>   80, :protocol => :tcp, :sources => ['0.0.0.0/0'] }
     61:   ]
     62: end
     63: aws_security_group "#{application}-db-sg"  do
    
    Compiled Resource:
    ------------------
    # Declared in /home/john/.chef/local-mode-cache/cache/cookbooks/elastichef/recipes/create.rb:56:in `from_file'
    
    aws_security_group("elastichef-app-sg") do
      action :create
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      id "elastichef-app-sg"
      security_group_id "sg-a1d408cc"
      declared_type :aws_security_group
      cookbook_name "elastichef"
      recipe_name "create"
      description "elastichef app servers"
      inbound_rules [{:ports=>22, :protocol=>:tcp, :sources=>["0.0.0.0/0"]}, {:ports=>80, :protocol=>:tcp, :sources=>["0.0.0.0/0"]}]
    end
```

If you try to delete the key, aws_security_group tells you that the key does not exist:

```
  * aws_security_group[elastichef-app-sg] action delete[2015-03-04T07:06:42-05:00] INFO: Processing aws_security_group[elastichef-app-sg] action delete (elastichef::destroy line 70)
    ================================================================================
    Error executing action `delete` on resource 'aws_security_group[elastichef-app-sg]'
    ================================================================================
    
    AWS::EC2::Errors::InvalidGroup::NotFound
    ----------------------------------------
    The security group 'sg-a1d408cc' does not exist
    
    Resource Declaration:
    ---------------------
    # In /home/john/.chef/local-mode-cache/cache/cookbooks/elastichef/recipes/destroy.rb
    
     70:           aws_security_group security_group do
     71:             action :delete
     72:           end
     73:         rescue Exception => msg
    
    Compiled Resource:
    ------------------
    # Declared in /home/john/.chef/local-mode-cache/cache/cookbooks/elastichef/recipes/destroy.rb:70:in `block (3 levels) in from_file'
    
    aws_security_group("elastichef-app-sg") do
      action [:delete]
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      id "elastichef-app-sg"
      security_group_id "sg-a1d408cc"
      declared_type :aws_security_group
      cookbook_name "elastichef"
      recipe_name "destroy"
    end
```

**Comment by john-casey** [comment]
The workaround is to delete the data_bag that is associated with this security group. This is created by the resource when it creates the aws security group.

**Comment by jkeiser** [comment]
Fixed in master!
