### ISSUE TITLE
Error when creating security group on VPC with outbound rule of 0.0.0.0/0

### ISSUE THREAD

**Issue by christinedraper** [chef/chef-provisioning-aws#129]
With 0.4, recipe below causes an error. Comment out the outbound rule and it will succeed.
```
vpc_resource=aws_vpc "provisioning-vpc" do
    cidr_block "10.0.1.0/24"
end
aws_security_group "provisioning-vpc-security-group" do
    inbound_rules  [
    {:ports => 3001, :protocol => :tcp, :sources => ["0.0.0.0/0" ] },
    {:ports => 1024..65535, :protocol => :tcp, :sources => [ "provisioning-vpc-security-group" ] } 
    ]
    outbound_rules [
    { :sources => ["0.0.0.0/0" ] }
    ]
    vpc "provisioning-vpc"
  end
```

```
NoMethodError: aws_security_group[provisioning-vpc-security-group] (@recipe_files::/home/christine/provisioning/aws/scripts/vpc_sg.rb line 13) had an error: NoMethodError: undefined method `map' for nil:NilClass
/home/christine/.chefdk/gem/ruby/2.1.0/gems/chef-provisioning-aws-0.4.0/lib/chef/provider/aws_security_group.rb:70:in `get_sources'
/home/christine/.chefdk/gem/ruby/2.1.0/gems/chef-provisioning-aws-0.4.0/lib/chef/provider/aws_security_group.rb:59:in `block (2 levels) in apply_rules'
/opt/chefdk/embedded/apps/chef/lib/chef/mixin/why_run.rb:52:in `call'
/opt/chefdk/embedded/apps/chef/lib/chef/mixin/why_run.rb:52:in `add_action'
/opt/chefdk/embedded/apps/chef/lib/chef/provider.rb:180:in `converge_by'
/home/christine/.chefdk/gem/ruby/2.1.0/gems/chef-provisioning-aws-0.4.0/lib/chef/provider/aws_security_group.rb:58:in `block in apply_rules'
/home/christine/.chefdk/gem/ruby/2.1.0/gems/chef-provisioning-aws-0.4.0/lib/chef/provider/aws_security_group.rb:56:in `each'
/home/christine/.chefdk/gem/ruby/2.1.0/gems/chef-provisioning-aws-0.4.0/lib/chef/provider/aws_security_group.rb:56:in `apply_rules'
/home/christine/.chefdk/gem/ruby/2.1.0/gems/chef-provisioning-aws-0.4.0/lib/chef/provider/aws_security_group.rb:23:in `block in <class:AwsSecurityGroup>'
/opt/chefdk/embedded/apps/chef/lib/chef/provider/lwrp_base.rb:60:in `instance_eval'
/opt/chefdk/embedded/apps/chef/lib/chef/provider/lwrp_base.rb:60:in `recipe_eval_with_update_check'
/opt/chefdk/embedded/apps/chef/lib/chef/provider/lwrp_base.rb:45:in `block in action'
/opt/chefdk/embedded/apps/chef/lib/chef/provider.rb:145:in `run_action'
<snip>
```

**Comment by christinedraper** [comment]
closed - :sources should be :destination in outbound rules
