### ISSUE TITLE
Second run on load balancer fails with AWS::Core::OptionGrammar::FormatError

### ISSUE THREAD

**Issue by christinedraper** [chef/chef-provisioning-aws#130]
Following fails on the second run:
```
load_balancer "appserver-elb" do
  load_balancer_options({:listeners=>[{:port=>3001, :protocol=>"HTTP", :instance_port=>3001, :instance_protocol=>"HTTP"}], 
  :availability_zones=>["us-west-2c", "us-west-2a", "us-west-2b"]})
end
```
with
```
Generated at 2015-03-11 21:15:54 -0500
AWS::Core::OptionGrammar::FormatError: expected enumerable value for option subnet_ids
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-v1-1.61.0/lib/aws/core/option_grammar.rb:240:in `validate'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-v1-1.61.0/lib/aws/core/option_grammar.rb:590:in `block in validate'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-v1-1.61.0/lib/aws/core/option_grammar.rb:586:in `each'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-v1-1.61.0/lib/aws/core/option_grammar.rb:586:in `validate'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-v1-1.61.0/lib/aws/core/option_grammar.rb:601:in `request_params'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-v1-1.61.0/lib/aws/core/query_request_builder.rb:37:in `populate_request'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-v1-1.61.0/lib/aws/core/client.rb:740:in `block (2 levels) in define_client_method'
```

**Comment by jkeiser** [comment]
This should be in much better shape on master--mind trying it now?  I'm not seeing that behavior but it doesn't mean you won't.  I tend to live in vpcs at the moment.

**Comment by christinedraper** [comment]
Still happening for me

**Comment by christinedraper** [comment]
Actually, I think it should just be:

```
 unless lb_options[:subnets].nil?
```

because it's not valid to have an empty array of subnets.

I tried this out and it seems to work (whether specifying availability zones, or subnets).
