### ISSUE TITLE
Update of subnet fails due to incorrect comparison

### ISSUE THREAD

**Issue by christinedraper** [chef/chef-provisioning-aws#137]
Rerunning the following:
```
  aws_subnet "provisioning-vpc-subnet-a" do
    cidr_block "10.0.1.0/26"
    vpc "provisioning-vpc"
   availability_zone "us-west-2a"
  end
```
Gives
```
RuntimeError: aws_subnet[provisioning-vpc-subnet-a] (@recipe_files::/home/christine/provisioning/aws/scripts/vpc_sg.rb line 11) had an error: RuntimeError: availability_zone for subnet provisioning-vpc-subnet-a is us-west-2a, but existing subnet (subnet-42d17835)'s availability_zone is us-west-2a.  Modification of subnet availability_zone is unsupported!
/home/christine/.chefdk/gem/ruby/2.1.0/gems/chef-provisioning-aws-0.4.0/lib/chef/provider/aws_subnet.rb:70:in `update_subnet'
/home/christine/.chefdk/gem/ruby/2.1.0/gems/chef-provisioning-aws-0.4.0/lib/chef/provider/aws_subnet.rb:11:in `block in <class:AwsSubnet>'

because subnet.availability_zone is an object not a string.

https://github.com/chef/chef-provisioning-aws/blob/master/lib/chef/provider/aws_subnet.rb#L69-L70

Should use subnet.availability_zone.name. Note also the error message has new_resource.availability_zone where it should have subnet.availability_zone.name

**Comment by zeroXten** [comment]
I'm getting this now again too, since going back from "jk/create_update_delete" to master.

**Comment by christinedraper** [comment]
This works OK now. Closing.
