### ISSUE TITLE
OpenSSL::SSL::SSLError connect error on machine converge

### ISSUE THREAD

**Issue by patrick-wright** [chef/chef-provisioning-aws#140]
chef-provisioning-aws master (27f4b4b9c8532b80b87996e87861b77202bf4551) 
chef-provisioning master (37b53d557af19f8b8947f802d48960849f39e134)

running `chef-client -z docs/examples/aws_ebs_volume_machine_types.rb -l info`

*recipe*
```ruby
require 'chef/provisioning/aws_driver'

with_driver 'aws::us-west-2'

aws_key = aws_key_pair 'ref-key-pair-ebs'

ref_machine = machine 'ref-machine-1'

# more stuff
```

*client output*
instance has been terminated
```
  * machine[ref-machine-1] action converge[2015-03-19T19:31:52-07:00] INFO: Processing machine[ref-machine-1] action converge (@recipe_files::/Users/patrickwright/Chef/github/chef/chef-provisioning-aws/docs/examples/aws_ebs_volume_machine_types.rb line 7)
[2015-03-19T19:31:52-07:00] INFO: Processing chef_node[ref-machine-1] action create (basic_chef_client::block line 57)
[2015-03-19T19:31:53-07:00] INFO: Executing sudo pwd on ubuntu@54.148.220.191
[2015-03-19T19:31:55-07:00] INFO: Completed pwd on ubuntu@54.148.220.191: exit status 0
[2015-03-19T19:31:55-07:00] INFO: Processing chef_node[ref-machine-1] action create (basic_chef_client::block line 57)
[2015-03-19T19:31:55-07:00] INFO: Executing sudo cp /etc/chef/client.pem /tmp/client.pem.137420064 on ubuntu@54.148.220.191
[2015-03-19T19:31:57-07:00] INFO: Completed cp /etc/chef/client.pem /tmp/client.pem.137420064 on ubuntu@54.148.220.191: exit status 0
[2015-03-19T19:31:57-07:00] INFO: Executing sudo chown ubuntu /tmp/client.pem.137420064 on ubuntu@54.148.220.191
[2015-03-19T19:31:58-07:00] INFO: Completed chown ubuntu /tmp/client.pem.137420064 on ubuntu@54.148.220.191: exit status 0
[2015-03-19T19:31:58-07:00] INFO: Executing sudo rm /tmp/client.pem.137420064 on ubuntu@54.148.220.191
[2015-03-19T19:31:58-07:00] INFO: Completed rm /tmp/client.pem.137420064 on ubuntu@54.148.220.191: exit status 0
[2015-03-19T19:31:58-07:00] INFO: Processing chef_client[ref-machine-1] action create (basic_chef_client::block line 131)
[2015-03-19T19:31:58-07:00] INFO: Processing chef_node[ref-machine-1] action create (basic_chef_client::block line 142)
[2015-03-19T19:31:58-07:00] INFO: Port forwarded: local URL http://localhost:8889 is available to 54.148.220.191 as http://localhost:8889 for the duration of this SSH connection.
[2015-03-19T19:31:58-07:00] INFO: Executing sudo ls -d /etc/chef/ohai/hints/ec2.json on ubuntu@54.148.220.191
[2015-03-19T19:31:58-07:00] INFO: Completed ls -d /etc/chef/ohai/hints/ec2.json on ubuntu@54.148.220.191: exit status 0
[2015-03-19T19:31:58-07:00] INFO: Executing sudo md5sum -b /etc/chef/ohai/hints/ec2.json on ubuntu@54.148.220.191
[2015-03-19T19:31:59-07:00] INFO: Completed md5sum -b /etc/chef/ohai/hints/ec2.json on ubuntu@54.148.220.191: exit status 0
[2015-03-19T19:31:59-07:00] INFO: Executing sudo ls -d /etc/chef/client.rb on ubuntu@54.148.220.191
[2015-03-19T19:31:59-07:00] INFO: Completed ls -d /etc/chef/client.rb on ubuntu@54.148.220.191: exit status 0
[2015-03-19T19:31:59-07:00] INFO: Executing sudo md5sum -b /etc/chef/client.rb on ubuntu@54.148.220.191
[2015-03-19T19:31:59-07:00] INFO: Completed md5sum -b /etc/chef/client.rb on ubuntu@54.148.220.191: exit status 0
[2015-03-19T19:31:59-07:00] INFO: Executing sudo chef-client -v on ubuntu@54.148.220.191
[2015-03-19T19:31:59-07:00] INFO: Completed chef-client -v on ubuntu@54.148.220.191: exit status 1


    ================================================================================
    Error executing action `converge` on resource 'machine[ref-machine-1]'
    ================================================================================

    OpenSSL::SSL::SSLError
    ----------------------
    SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed

    Resource Declaration:
    ---------------------
    # In /Users/patrickwright/Chef/github/chef/chef-provisioning-aws/docs/examples/aws_ebs_volume_machine_types.rb

      7: ref_machine = machine 'ref-machine-1'
      8:

    Compiled Resource:
    ------------------
    # Declared in /Users/patrickwright/Chef/github/chef/chef-provisioning-aws/docs/examples/aws_ebs_volume_machine_types.rb:7:in `from_file'

    machine("ref-machine-1") do
      action :converge
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      chef_server {:chef_server_url=>"http://localhost:8889", :options=>{:client_name=>"remwright01", :signing_key_filename=>nil}}
      driver "aws::us-west-2"
      declared_type :machine
      cookbook_name "@recipe_files"
      recipe_name "/Users/patrickwright/Chef/github/chef/chef-provisioning-aws/docs/examples/aws_ebs_volume_machine_types.rb"
    end
```

*stacktrace*
```
OpenSSL::SSL::SSLError: machine[ref-machine-1] (@recipe_files::/Users/patrickwright/Chef/github/chef/chef-provisioning-aws/docs/examples/aws_ebs_volume_machine_types.rb line 7) had an error: OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed
/Users/patrickwright/.rbenv/versions/2.1.1/lib/ruby/2.1.0/net/http.rb:920:in `connect'
/Users/patrickwright/.rbenv/versions/2.1.1/lib/ruby/2.1.0/net/http.rb:920:in `block in connect'
/Users/patrickwright/.rbenv/versions/2.1.1/lib/ruby/2.1.0/timeout.rb:76:in `timeout'
/Users/patrickwright/.rbenv/versions/2.1.1/lib/ruby/2.1.0/net/http.rb:920:in `connect'
/Users/patrickwright/.rbenv/versions/2.1.1/lib/ruby/2.1.0/net/http.rb:863:in `do_start'
/Users/patrickwright/.rbenv/versions/2.1.1/lib/ruby/2.1.0/net/http.rb:852:in `start'
/Users/patrickwright/.rbenv/versions/2.1.1/lib/ruby/2.1.0/net/http.rb:583:in `start'
/Users/patrickwright/.rbenv/versions/2.1.1/lib/ruby/2.1.0/net/http.rb:478:in `get_response'
/Users/patrickwright/.rbenv/versions/2.1.1/lib/ruby/2.1.0/net/http.rb:455:in `get'
/Users/patrickwright/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/bundler/gems/chef-provisioning-37b53d557af1/lib/chef/provisioning/convergence_strategy/install_sh.rb:67:in `setup_convergence'
/Users/patrickwright/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/bundler/gems/chef-provisioning-37b53d557af1/lib/chef/provisioning/machine/basic_machine.rb:17:in `setup_convergence'
/Users/patrickwright/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/bundler/gems/chef-provisioning-37b53d557af1/lib/chef/provider/machine.rb:57:in `block in <class:Machine>'
/Users/patrickwright/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/chef-12.0.3/lib/chef/provider/lwrp_base.rb:60:in `instance_eval'
/Users/patrickwright/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/chef-12.0.3/lib/chef/provider/lwrp_base.rb:60:in `recipe_eval_with_update_check'
/Users/patrickwright/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/chef-12.0.3/lib/chef/provider/lwrp_base.rb:45:in `block in action'
/Users/patrickwright/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/chef-12.0.3/lib/chef/provider.rb:145:in `run_action'
/Users/patrickwright/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/chef-12.0.3/lib/chef/resource.rb:582:in `run_action'
/Users/patrickwright/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/chef-12.0.3/lib/chef/runner.rb:49:in `run_action'
/Users/patrickwright/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/chef-12.0.3/lib/chef/runner.rb:81:in `block (2 levels) in converge'
/Users/patrickwright/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/chef-12.0.3/lib/chef/runner.rb:81:in `each'
/Users/patrickwright/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/chef-12.0.3/lib/chef/runner.rb:81:in `block in converge'
/Users/patrickwright/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/chef-12.0.3/lib/chef/resource_collection/resource_list.rb:83:in `block in execute_each_resource'
/Users/patrickwright/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/chef-12.0.3/lib/chef/resource_collection/stepable_iterator.rb:116:in `call'
/Users/patrickwright/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/chef-12.0.3/lib/chef/resource_collection/stepable_iterator.rb:116:in `call_iterator_block'
/Users/patrickwright/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/chef-12.0.3/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
/Users/patrickwright/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/chef-12.0.3/lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
/Users/patrickwright/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/chef-12.0.3/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
/Users/patrickwright/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/chef-12.0.3/lib/chef/resource_collection/resource_list.rb:81:in `execute_each_resource'
/Users/patrickwright/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/chef-12.0.3/lib/chef/runner.rb:80:in `converge'
/Users/patrickwright/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/chef-12.0.3/lib/chef/client.rb:315:in `converge'
/Users/patrickwright/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/chef-12.0.3/lib/chef/client.rb:400:in `block in run'
/Users/patrickwright/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/chef-12.0.3/lib/chef/client.rb:399:in `catch'
/Users/patrickwright/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/chef-12.0.3/lib/chef/client.rb:399:in `run'
/Users/patrickwright/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/chef-12.0.3/lib/chef/application.rb:261:in `block in fork_chef_client'
/Users/patrickwright/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/chef-12.0.3/lib/chef/application.rb:249:in `fork'
/Users/patrickwright/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/chef-12.0.3/lib/chef/application.rb:249:in `fork_chef_client'
/Users/patrickwright/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/chef-12.0.3/lib/chef/application.rb:215:in `block in run_chef_client'
/Users/patrickwright/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/chef-12.0.3/lib/chef/local_mode.rb:38:in `with_server_connectivity'
/Users/patrickwright/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/chef-12.0.3/lib/chef/application.rb:201:in `run_chef_client'
/Users/patrickwright/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/chef-12.0.3/lib/chef/application/client.rb:355:in `block in interval_run_chef_client'
/Users/patrickwright/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/chef-12.0.3/lib/chef/application/client.rb:345:in `loop'
/Users/patrickwright/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/chef-12.0.3/lib/chef/application/client.rb:345:in `interval_run_chef_client'
/Users/patrickwright/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/chef-12.0.3/lib/chef/application/client.rb:335:in `run_application'
/Users/patrickwright/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/chef-12.0.3/lib/chef/application.rb:58:in `run'
/Users/patrickwright/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/chef-12.0.3/bin/chef-client:26:in `<top (required)>'
/Users/patrickwright/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/bin/chef-client:23:in `load'
/Users/patrickwright/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/bin/chef-client:23:in `<main>'
```

**Comment by bplunkert** [comment]
hi @patrick-wright I am experiencing a similar issue with chef-provisioning on Digital Ocean. Did you find a cause, solution or workaround for this issue?

**Comment by patrick-wright** [comment]
Yes.  It actually turned out that I need to perform a system update.  There was an SSL issue that was corrected along with the updates.
