### ISSUE TITLE
Cloning resource attributes warnings at start of chef run

### ISSUE THREAD

**Issue by patrick-wright** [chef/chef-provisioning-aws#159]
```
[2015-03-27T14:27:39-07:00] WARN: Cloning resource attributes for aws_network_interface[ref-eni-1] (no AWS object id) from prior resource (CHEF-3694)
[2015-03-27T14:27:39-07:00] WARN: Previous aws_network_interface[ref-eni-1] (no AWS object id): /Users/patrickwright/Chef/github/chef/chef-provisioning-aws-eni/docs/examples/aws_network_interface.rb:46:in `from_file'
[2015-03-27T14:27:39-07:00] WARN: Current  aws_network_interface[ref-eni-1] (no AWS object id): /Users/patrickwright/Chef/github/chef/chef-provisioning-aws-eni/docs/examples/aws_network_interface.rb:51:in `from_file'
[2015-03-27T14:27:39-07:00] WARN: Cloning resource attributes for aws_network_interface[ref-eni-1] (no AWS object id) from prior resource (CHEF-3694)
[2015-03-27T14:27:39-07:00] WARN: Previous aws_network_interface[ref-eni-1] (no AWS object id): /Users/patrickwright/Chef/github/chef/chef-provisioning-aws-eni/docs/examples/aws_network_interface.rb:51:in `from_file'
[2015-03-27T14:27:39-07:00] WARN: Current  aws_network_interface[ref-eni-1] (no AWS object id): /Users/patrickwright/Chef/github/chef/chef-provisioning-aws-eni/docs/examples/aws_network_interface.rb:64:in `from_file'
[2015-03-27T14:27:39-07:00] WARN: Cloning resource attributes for aws_subnet[ref-subnet-eni] (no AWS object id) from prior resource (CHEF-3694)
[2015-03-27T14:27:39-07:00] WARN: Previous aws_subnet[ref-subnet-eni] (no AWS object id): /Users/patrickwright/Chef/github/chef/chef-provisioning-aws-eni/docs/examples/aws_network_interface.rb:32:in `from_file'
[2015-03-27T14:27:39-07:00] WARN: Current  aws_subnet[ref-subnet-eni] (no AWS object id): /Users/patrickwright/Chef/github/chef/chef-provisioning-aws-eni/docs/examples/aws_network_interface.rb:72:in `from_file'
[2015-03-27T14:27:39-07:00] WARN: Cloning resource attributes for aws_route_table[ref-public-eni] (no AWS object id) from prior resource (CHEF-3694)
[2015-03-27T14:27:39-07:00] WARN: Previous aws_route_table[ref-public-eni] (no AWS object id): /Users/patrickwright/Chef/github/chef/chef-provisioning-aws-eni/docs/examples/aws_network_interface.rb:27:in `from_file'
[2015-03-27T14:27:39-07:00] WARN: Current  aws_route_table[ref-public-eni] (no AWS object id): /Users/patrickwright/Chef/github/chef/chef-provisioning-aws-eni/docs/examples/aws_network_interface.rb:76:in `from_file'
[2015-03-27T14:27:39-07:00] WARN: Cloning resource attributes for aws_security_group[ref-sg2-eni] (no AWS object id) from prior resource (CHEF-3694)
[2015-03-27T14:27:39-07:00] WARN: Previous aws_security_group[ref-sg2-eni] (no AWS object id): /Users/patrickwright/Chef/github/chef/chef-provisioning-aws-eni/docs/examples/aws_network_interface.rb:21:in `from_file'
[2015-03-27T14:27:39-07:00] WARN: Current  aws_security_group[ref-sg2-eni] (no AWS object id): /Users/patrickwright/Chef/github/chef/chef-provisioning-aws-eni/docs/examples/aws_network_interface.rb:80:in `from_file'
[2015-03-27T14:27:39-07:00] WARN: Cloning resource attributes for aws_security_group[ref-sg1-eni] (no AWS object id) from prior resource (CHEF-3694)
[2015-03-27T14:27:39-07:00] WARN: Previous aws_security_group[ref-sg1-eni] (no AWS object id): /Users/patrickwright/Chef/github/chef/chef-provisioning-aws-eni/docs/examples/aws_network_interface.rb:16:in `from_file'
[2015-03-27T14:27:39-07:00] WARN: Current  aws_security_group[ref-sg1-eni] (no AWS object id): /Users/patrickwright/Chef/github/chef/chef-provisioning-aws-eni/docs/examples/aws_network_interface.rb:84:in `from_file'
[2015-03-27T14:27:39-07:00] WARN: Cloning resource attributes for aws_vpc[ref-vpc-eni] (no AWS object id) from prior resource (CHEF-3694)
[2015-03-27T14:27:39-07:00] WARN: Previous aws_vpc[ref-vpc-eni] (no AWS object id): /Users/patrickwright/Chef/github/chef/chef-provisioning-aws-eni/docs/examples/aws_network_interface.rb:9:in `from_file'
[2015-03-27T14:27:39-07:00] WARN: Current  aws_vpc[ref-vpc-eni] (no AWS object id): /Users/patrickwright/Chef/github/chef/chef-provisioning-aws-eni/docs/examples/aws_network_interface.rb:88:in `from_file'
[2015-03-27T14:27:39-07:00] WARN: Cloning resource attributes for aws_dhcp_options[ref-dhcp-options-eni] (no AWS object id) from prior resource (CHEF-3694)
[2015-03-27T14:27:39-07:00] WARN: Previous aws_dhcp_options[ref-dhcp-options-eni] (no AWS object id): /Users/patrickwright/Chef/github/chef/chef-provisioning-aws-eni/docs/examples/aws_network_interface.rb:7:in `from_file'
[2015-03-27T14:27:39-07:00] WARN: Current  aws_dhcp_options[ref-dhcp-options-eni] (no AWS object id): /Users/patrickwright/Chef/github/chef/chef-provisioning-aws-eni/docs/examples/aws_network_interface.rb:92:in `from_file'
```

**Comment by patrick-wright** [comment]
@jkeiser @tyler-ball

**Comment by tyler-ball** [comment]
https://github.com/chef/chef-provisioning-aws/blob/master/lib/chef/provisioning/aws_driver/super_lwrp.rb#L38-L40

This used to work, but apparently Chef no longer has a `load_prior_resource` method...

**Comment by tyler-ball** [comment]
This changed in https://github.com/chef/chef/commit/5a2f19a85fbee9f4517aa471378e40cf32d030e0 - now the `ResourceBuilder` looks up the `prior_resource`.

This isn't going to be as easy to overwrite because now the `Resource` has no direct control over how the prior resource is looked up.
