### ISSUE TITLE
NoMethodError: undefined method `id' for "ami-e7f8d6d7" for aws_launch_configuration

### ISSUE THREAD

**Issue by christinedraper** [chef/chef-provisioning-aws#160]
```
Generated at 2015-03-28 15:23:19 -0500
NoMethodError: aws_launch_configuration[testappserver-aws1_config] (@recipe_files::/home/christine/git/topo-provision/gen/aws_deploy.rb line 40) had an error: NoMethodError: undefined method `id' for "ami-e7f8d6d7":String
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-provisioning-aws-0.5.0/lib/chef/provider/aws_launch_configuration.rb:26:in `update_aws_object'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-provisioning-aws-0.5.0/lib/chef/provisioning/aws_driver/aws_provider.rb:109:in `block in <class:AWSProvider>'
```
Looking at aws_launch_configuration.rb:26, I'd think that it should use `(#{image})` not `(#{image.id})`
i.e.
```
raise "#{new_resource.to_s}.image = #{new_resource.image} (#{image}), but actual launch configuration has image set to #{launch_configuration.image_id}.  Cannot be modified!"
```

**Comment by christinedraper** [comment]
Believe this has been fixed/superceded by refactoring.
