### ISSUE TITLE
machine :destroy RuntimeError when aws_instance resource has been used in the recipe

### ISSUE THREAD

**Issue by patrick-wright** [chef/chef-provisioning-aws#189]
### recipe
```ruby
require 'chef/provisioning/aws_driver'

with_driver 'aws::us-west-2'

machine 'ref-machine-1' do
  action :allocate
end

aws_instance 'ref-machine-1' do
  aws_tags :marco => 'polo', :happyhappy => 'joyjoy'
end

aws_instance 'ref-machine-1' do
  aws_tags :othercustomtags => 'byebye'
end

aws_instance 'ref-machine-1' do
  aws_tags :Name => 'new-name'
end

machine 'ref-machine-1' do
  action :destroy
end

# Same error using:
# aws_instance 'ref-machine-1' do
#   action :destroy
# end
```

### client
```
================================================================================
    Error executing action `destroy` on resource 'machine[ref-machine-1]'
    ================================================================================

    RuntimeError
    ------------
    Switching a machine's driver from  to aws::us-west-2 is not currently supported!  Use machine :destroy and then re-create the machine on the new driver.

    Resource Declaration:
    ---------------------
    # In /Users/patrickwright/Chef/github/chef/chef-provisioning-aws/docs/examples/aws_tags.rb

     21: machine 'ref-machine-1' do
     22:   action :destroy
     23: end

    Compiled Resource:
    ------------------
    # Declared in /Users/patrickwright/Chef/github/chef/chef-provisioning-aws/docs/examples/aws_tags.rb:21:in `from_file'

    machine("ref-machine-1") do
      action [:destroy]
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      chef_server {:chef_server_url=>"http://localhost:8889", :options=>{:client_name=>"remwright01", :signing_key_filename=>nil}}
      driver "aws::us-west-2"
      declared_type :machine
      cookbook_name "@recipe_files"
      recipe_name "/Users/patrickwright/Chef/github/chef/chef-provisioning-aws/docs/examples/aws_tags.rb"
    end
```

### stacktrace
```
RuntimeError: machine[ref-machine-1] (@recipe_files::/Users/patrickwright/Chef/github/chef/chef-provisioning-aws/docs/examples/aws_tags.rb line 21) had an error: RuntimeError: Switching a machine's driver from  to aws::us-west-2 is not currently supported!  Use machine :destroy and then re-create the machine on the new driver.
/Users/patrickwright/Chef/github/chef/chef-provisioning-aws/lib/chef/provisioning/aws_driver/driver.rb:607:in `instance_for'
/Users/patrickwright/Chef/github/chef/chef-provisioning-aws/lib/chef/provisioning/aws_driver/driver.rb:473:in `destroy_machine'
/Users/patrickwright/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/chef-provisioning-1.1.1/lib/chef/provider/machine.rb:95:in `block in <class:Machine>'
/Users/patrickwright/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/chef-12.2.1/lib/chef/provider/lwrp_base.rb:60:in `instance_eval'
/Users/patrickwright/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/chef-12.2.1/lib/chef/provider/lwrp_base.rb:60:in `recipe_eval_with_update_check'
/Users/patrickwright/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/chef-12.2.1/lib/chef/provider/lwrp_base.rb:45:in `block in action'
/Users/patrickwright/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/chef-12.2.1/lib/chef/provider.rb:145:in `run_action'
/Users/patrickwright/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/chef-12.2.1/lib/chef/resource.rb:561:in `run_action'
/Users/patrickwright/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/chef-12.2.1/lib/chef/runner.rb:49:in `run_action'
/Users/patrickwright/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/chef-12.2.1/lib/chef/runner.rb:81:in `block (2 levels) in converge'
/Users/patrickwright/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/chef-12.2.1/lib/chef/runner.rb:81:in `each'
/Users/patrickwright/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/chef-12.2.1/lib/chef/runner.rb:81:in `block in converge'
/Users/patrickwright/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/chef-12.2.1/lib/chef/resource_collection/resource_list.rb:83:in `block in execute_each_resource'
/Users/patrickwright/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/chef-12.2.1/lib/chef/resource_collection/stepable_iterator.rb:116:in `call'
/Users/patrickwright/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/chef-12.2.1/lib/chef/resource_collection/stepable_iterator.rb:116:in `call_iterator_block'
/Users/patrickwright/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/chef-12.2.1/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
/Users/patrickwright/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/chef-12.2.1/lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
/Users/patrickwright/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/chef-12.2.1/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
/Users/patrickwright/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/chef-12.2.1/lib/chef/resource_collection/resource_list.rb:81:in `execute_each_resource'
/Users/patrickwright/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/chef-12.2.1/lib/chef/runner.rb:80:in `converge'
/Users/patrickwright/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/chef-12.2.1/lib/chef/client.rb:331:in `block in converge'
/Users/patrickwright/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/chef-12.2.1/lib/chef/client.rb:326:in `catch'
/Users/patrickwright/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/chef-12.2.1/lib/chef/client.rb:326:in `converge'
/Users/patrickwright/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/chef-12.2.1/lib/chef/client.rb:345:in `converge_and_save'
/Users/patrickwright/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/chef-12.2.1/lib/chef/client.rb:449:in `run'
/Users/patrickwright/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/chef-12.2.1/lib/chef/application.rb:271:in `block in fork_chef_client'
/Users/patrickwright/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/chef-12.2.1/lib/chef/application.rb:259:in `fork'
/Users/patrickwright/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/chef-12.2.1/lib/chef/application.rb:259:in `fork_chef_client'
/Users/patrickwright/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/chef-12.2.1/lib/chef/application.rb:225:in `block in run_chef_client'
/Users/patrickwright/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/chef-12.2.1/lib/chef/local_mode.rb:38:in `with_server_connectivity'
/Users/patrickwright/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/chef-12.2.1/lib/chef/application.rb:213:in `run_chef_client'
/Users/patrickwright/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/chef-12.2.1/lib/chef/application/client.rb:392:in `block in interval_run_chef_client'
/Users/patrickwright/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/chef-12.2.1/lib/chef/application/client.rb:382:in `loop'
/Users/patrickwright/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/chef-12.2.1/lib/chef/application/client.rb:382:in `interval_run_chef_client'
/Users/patrickwright/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/chef-12.2.1/lib/chef/application/client.rb:372:in `run_application'
/Users/patrickwright/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/chef-12.2.1/lib/chef/application.rb:60:in `run'
/Users/patrickwright/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/chef-12.2.1/bin/chef-client:26:in `<top (required)>'
/Users/patrickwright/.rbenv/versions/2.1.5/bin/chef-client:23:in `load'
/Users/patrickwright/.rbenv/versions/2.1.5/bin/chef-client:23:in `<main>'
```

**Comment by patrick-wright** [comment]
@tyler-ball
