### ISSUE TITLE
(basic_chef_client::block line 57) had an error: Net::HTTPServerException: 404 "Not Found"

### ISSUE THREAD

**Issue by etagwerker** [chef/chef-provisioning-aws#217]
Hi! 

I ran into this issue while building a machine in my VPC. 

Here is the backtrace:

```
[2015-06-01T17:30:53-03:00] DEBUG: ---- HTTP Request Body ----
[2015-06-01T17:30:53-03:00] DEBUG: {"name":"api","json_class":"Chef::Node","chef_type":"node","chef_environment":"_default","override":{},"normal":{"tags":["api","ombulabs"],"chef_provisioning":{"reference":{"driver_version":"1.2.1","allocated_at":"2015-06-01 20:30:51 UTC","host_node":"https://chef.ombulabs.com/organizations/ombulabs/nodes/","image_id":"ami-17471c27","instance_id":"i-ed01201b","key_name":"cluster","ssh_username":"ubuntu"},"driver_url":"aws::us-west-2"}},"default":{},"automatic":{},"run_list":[]}
[2015-06-01T17:30:53-03:00] DEBUG: ---- End HTTP Request Body ----
[2015-06-01T17:30:53-03:00] DEBUG: Chef::HTTP calling Chef::HTTP::RemoteRequestID#handle_response
[2015-06-01T17:30:53-03:00] DEBUG: Chef::HTTP calling Chef::HTTP::Authenticator#handle_response
[2015-06-01T17:30:53-03:00] DEBUG: Chef::HTTP calling Chef::HTTP::Decompressor#handle_response
[2015-06-01T17:30:53-03:00] DEBUG: decompressing gzip response
[2015-06-01T17:30:53-03:00] DEBUG: Chef::HTTP calling Chef::HTTP::CookieManager#handle_response
[2015-06-01T17:30:53-03:00] DEBUG: Chef::HTTP calling Chef::HTTP::JSONOutput#handle_response
[2015-06-01T17:30:53-03:00] DEBUG: Expected JSON response, but got content-type 'text/html'
[2015-06-01T17:30:53-03:00] DEBUG: Chef::HTTP calling Chef::HTTP::JSONInput#handle_response
[2015-06-01T17:30:53-03:00] INFO: HTTP Request Returned 404 Not Found: 
[2015-06-01T17:30:53-03:00] INFO: Running queued delayed notifications before re-raising exception

    ================================================================================
    Error executing action `converge` on resource 'machine[api]'
    ================================================================================
    
    Net::HTTPServerException
    ------------------------
    chef_node[api] (basic_chef_client::block line 57) had an error: Net::HTTPServerException: 404 "Not Found"
    
    Resource Declaration:
    ---------------------
    # In /var/chef/cache/cookbooks/api/recipes/default.rb
    
     55: machine 'api' do
     56:   tag 'api'
     57:   tag 'ombulabs'
     58:   # ohai_hints 'ec2' => '{}'
     59:   # action :converge
     60:   # converge true
     61: end
    
    Compiled Resource:
    ------------------
    # Declared in /var/chef/cache/cookbooks/api/recipes/default.rb:55:in `from_file'
    
    machine("api") do
      action :converge
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      chef_server {:chef_server_url=>"https://chef.ombulabs.com", :options=>{:client_name=>"admin", :signing_key_filename=>"/Users/etagwerker/Projects/chef-repo/.chef/admin.pem"}}
      driver "aws::us-west-2"
      machine_options {:ssh_username=>"ubuntu", :use_private_ip_for_ssh=>false, :bootstrap_options=>{:key_name=>"cluster", :image_id=>"ami-17471c27", :instance_type=>"t1.micro"}}
      declared_type :machine
      cookbook_name "api"
      recipe_name "default"
      attribute_modifiers [["tags", #<Proc:0x007f82128379f8@/Users/etagwerker/.rvm/gems/ruby-2.1.2@chef/gems/cheffish-1.2/lib/cheffish.rb:149>], ["tags", #<Proc:0x007f82128378e0@/Users/etagwerker/.rvm/gems/ruby-2.1.2@chef/gems/cheffish-1.2/lib/cheffish.rb:149>]]
    end
    
[2015-06-01T17:30:53-03:00] INFO: Running queued delayed notifications before re-raising exception
[2015-06-01T17:30:53-03:00] DEBUG: Re-raising exception: Net::HTTPServerException - machine[api] (api::default line 55) had an error: Net::HTTPServerException: chef_node[api] (basic_chef_client::block line 57) had an error: Net::HTTPServerException: 404 "Not Found"
/Users/etagwerker/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/net/http/response.rb:119:in `error!'
  /Users/etagwerker/.rvm/gems/ruby-2.1.2@chef/gems/chef-12.3.0/lib/chef/http.rb:145:in `request'
  /Users/etagwerker/.rvm/gems/ruby-2.1.2@chef/gems/chef-12.3.0/lib/chef/http.rb:126:in `post'
  /Users/etagwerker/.rvm/gems/ruby-2.1.2@chef/gems/cheffish-1.2/lib/chef/provider/chef_node.rb:24:in `block (2 levels) in <class:ChefNode>'
  /Users/etagwerker/.rvm/gems/ruby-2.1.2@chef/gems/chef-12.3.0/lib/chef/mixin/why_run.rb:52:in `call'
  /Users/etagwerker/.rvm/gems/ruby-2.1.2@chef/gems/chef-12.3.0/lib/chef/mixin/why_run.rb:52:in `add_action'
  /Users/etagwerker/.rvm/gems/ruby-2.1.2@chef/gems/chef-12.3.0/lib/chef/provider.rb:165:in `converge_by'
  /Users/etagwerker/.rvm/gems/ruby-2.1.2@chef/gems/cheffish-1.2/lib/chef/provider/chef_node.rb:23:in `block in <class:ChefNode>'
  /Users/etagwerker/.rvm/gems/ruby-2.1.2@chef/gems/chef-12.3.0/lib/chef/provider/lwrp_base.rb:138:in `instance_eval'
  /Users/etagwerker/.rvm/gems/ruby-2.1.2@chef/gems/chef-12.3.0/lib/chef/provider/lwrp_base.rb:138:in `block in action'
  /Users/etagwerker/.rvm/gems/ruby-2.1.2@chef/gems/chef-12.3.0/lib/chef/provider.rb:130:in `run_action'
  /Users/etagwerker/.rvm/gems/ruby-2.1.2@chef/gems/chef-12.3.0/lib/chef/resource.rb:562:in `run_action'
  /Users/etagwerker/.rvm/gems/ruby-2.1.2@chef/gems/chef-12.3.0/lib/chef/runner.rb:49:in `run_action'
  /Users/etagwerker/.rvm/gems/ruby-2.1.2@chef/gems/chef-12.3.0/lib/chef/runner.rb:81:in `block (2 levels) in converge'
  /Users/etagwerker/.rvm/gems/ruby-2.1.2@chef/gems/chef-12.3.0/lib/chef/runner.rb:81:in `each'
  /Users/etagwerker/.rvm/gems/ruby-2.1.2@chef/gems/chef-12.3.0/lib/chef/runner.rb:81:in `block in converge'
  /Users/etagwerker/.rvm/gems/ruby-2.1.2@chef/gems/chef-12.3.0/lib/chef/resource_collection/resource_list.rb:83:in `block in execute_each_resource'
  /Users/etagwerker/.rvm/gems/ruby-2.1.2@chef/gems/chef-12.3.0/lib/chef/resource_collection/stepable_iterator.rb:116:in `call'
  /Users/etagwerker/.rvm/gems/ruby-2.1.2@chef/gems/chef-12.3.0/lib/chef/resource_collection/stepable_iterator.rb:116:in `call_iterator_block'
  /Users/etagwerker/.rvm/gems/ruby-2.1.2@chef/gems/chef-12.3.0/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
  /Users/etagwerker/.rvm/gems/ruby-2.1.2@chef/gems/chef-12.3.0/lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
  /Users/etagwerker/.rvm/gems/ruby-2.1.2@chef/gems/chef-12.3.0/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
  /Users/etagwerker/.rvm/gems/ruby-2.1.2@chef/gems/chef-12.3.0/lib/chef/resource_collection/resource_list.rb:81:in `execute_each_resource'
  /Users/etagwerker/.rvm/gems/ruby-2.1.2@chef/gems/chef-12.3.0/lib/chef/runner.rb:80:in `converge'
  /Users/etagwerker/.rvm/gems/ruby-2.1.2@chef/gems/cheffish-1.2/lib/cheffish/basic_chef_client.rb:69:in `block in converge'
  /Users/etagwerker/.rvm/gems/ruby-2.1.2@chef/gems/cheffish-1.2/lib/cheffish/basic_chef_client.rb:133:in `call'
  /Users/etagwerker/.rvm/gems/ruby-2.1.2@chef/gems/cheffish-1.2/lib/cheffish/basic_chef_client.rb:133:in `with_chef_config'
  /Users/etagwerker/.rvm/gems/ruby-2.1.2@chef/gems/cheffish-1.2/lib/cheffish/basic_chef_client.rb:68:in `converge'
  /Users/etagwerker/.rvm/gems/ruby-2.1.2@chef/gems/cheffish-1.2/lib/cheffish/basic_chef_client.rb:109:in `converge_block'
  /Users/etagwerker/.rvm/gems/ruby-2.1.2@chef/gems/chef-provisioning-1.2.0/lib/chef/provisioning.rb:12:in `inline_resource'
  /Users/etagwerker/.rvm/gems/ruby-2.1.2@chef/gems/chef-provisioning-1.2.0/lib/chef/provisioning/chef_managed_entry_store.rb:55:in `save_data'
  /Users/etagwerker/.rvm/gems/ruby-2.1.2@chef/gems/chef-provisioning-1.2.0/lib/chef/provisioning/managed_entry.rb:69:in `save'
  /Users/etagwerker/.rvm/gems/ruby-2.1.2@chef/gems/chef-provisioning-1.2.0/lib/chef/provider/machine.rb:33:in `block in <class:Machine>'
  /Users/etagwerker/.rvm/gems/ruby-2.1.2@chef/gems/chef-12.3.0/lib/chef/provider/lwrp_base.rb:60:in `instance_eval'
  /Users/etagwerker/.rvm/gems/ruby-2.1.2@chef/gems/chef-12.3.0/lib/chef/provider/lwrp_base.rb:60:in `recipe_eval_with_update_check'
  /Users/etagwerker/.rvm/gems/ruby-2.1.2@chef/gems/chef-12.3.0/lib/chef/provider/lwrp_base.rb:45:in `block in action'
  /Users/etagwerker/.rvm/gems/ruby-2.1.2@chef/gems/chef-provisioning-1.2.0/lib/chef/provider/machine.rb:37:in `block in <class:Machine>'
  /Users/etagwerker/.rvm/gems/ruby-2.1.2@chef/gems/chef-12.3.0/lib/chef/provider/lwrp_base.rb:60:in `instance_eval'
  /Users/etagwerker/.rvm/gems/ruby-2.1.2@chef/gems/chef-12.3.0/lib/chef/provider/lwrp_base.rb:60:in `recipe_eval_with_update_check'
  /Users/etagwerker/.rvm/gems/ruby-2.1.2@chef/gems/chef-12.3.0/lib/chef/provider/lwrp_base.rb:45:in `block in action'
  /Users/etagwerker/.rvm/gems/ruby-2.1.2@chef/gems/chef-provisioning-1.2.0/lib/chef/provider/machine.rb:55:in `block in <class:Machine>'
  /Users/etagwerker/.rvm/gems/ruby-2.1.2@chef/gems/chef-12.3.0/lib/chef/provider/lwrp_base.rb:60:in `instance_eval'
  /Users/etagwerker/.rvm/gems/ruby-2.1.2@chef/gems/chef-12.3.0/lib/chef/provider/lwrp_base.rb:60:in `recipe_eval_with_update_check'
  /Users/etagwerker/.rvm/gems/ruby-2.1.2@chef/gems/chef-12.3.0/lib/chef/provider/lwrp_base.rb:45:in `block in action'
  /Users/etagwerker/.rvm/gems/ruby-2.1.2@chef/gems/chef-12.3.0/lib/chef/provider.rb:130:in `run_action'
  /Users/etagwerker/.rvm/gems/ruby-2.1.2@chef/gems/chef-12.3.0/lib/chef/resource.rb:562:in `run_action'
  /Users/etagwerker/.rvm/gems/ruby-2.1.2@chef/gems/chef-12.3.0/lib/chef/runner.rb:49:in `run_action'
  /Users/etagwerker/.rvm/gems/ruby-2.1.2@chef/gems/chef-12.3.0/lib/chef/runner.rb:81:in `block (2 levels) in converge'
  /Users/etagwerker/.rvm/gems/ruby-2.1.2@chef/gems/chef-12.3.0/lib/chef/runner.rb:81:in `each'
  /Users/etagwerker/.rvm/gems/ruby-2.1.2@chef/gems/chef-12.3.0/lib/chef/runner.rb:81:in `block in converge'
  /Users/etagwerker/.rvm/gems/ruby-2.1.2@chef/gems/chef-12.3.0/lib/chef/resource_collection/resource_list.rb:83:in `block in execute_each_resource'
  /Users/etagwerker/.rvm/gems/ruby-2.1.2@chef/gems/chef-12.3.0/lib/chef/resource_collection/stepable_iterator.rb:116:in `call'
  /Users/etagwerker/.rvm/gems/ruby-2.1.2@chef/gems/chef-12.3.0/lib/chef/resource_collection/stepable_iterator.rb:116:in `call_iterator_block'
  /Users/etagwerker/.rvm/gems/ruby-2.1.2@chef/gems/chef-12.3.0/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
  /Users/etagwerker/.rvm/gems/ruby-2.1.2@chef/gems/chef-12.3.0/lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
  /Users/etagwerker/.rvm/gems/ruby-2.1.2@chef/gems/chef-12.3.0/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
  /Users/etagwerker/.rvm/gems/ruby-2.1.2@chef/gems/chef-12.3.0/lib/chef/resource_collection/resource_list.rb:81:in `execute_each_resource'
  /Users/etagwerker/.rvm/gems/ruby-2.1.2@chef/gems/chef-12.3.0/lib/chef/runner.rb:80:in `converge'
  /Users/etagwerker/.rvm/gems/ruby-2.1.2@chef/gems/chef-12.3.0/lib/chef/client.rb:339:in `block in converge'
  /Users/etagwerker/.rvm/gems/ruby-2.1.2@chef/gems/chef-12.3.0/lib/chef/client.rb:334:in `catch'
  /Users/etagwerker/.rvm/gems/ruby-2.1.2@chef/gems/chef-12.3.0/lib/chef/client.rb:334:in `converge'
  /Users/etagwerker/.rvm/gems/ruby-2.1.2@chef/gems/chef-12.3.0/lib/chef/client.rb:353:in `converge_and_save'
  /Users/etagwerker/.rvm/gems/ruby-2.1.2@chef/gems/chef-12.3.0/lib/chef/client.rb:457:in `run'
  /Users/etagwerker/.rvm/gems/ruby-2.1.2@chef/gems/chef-12.3.0/lib/chef/application.rb:271:in `block in fork_chef_client'
  /Users/etagwerker/.rvm/gems/ruby-2.1.2@chef/gems/chef-12.3.0/lib/chef/application.rb:259:in `fork'
  /Users/etagwerker/.rvm/gems/ruby-2.1.2@chef/gems/chef-12.3.0/lib/chef/application.rb:259:in `fork_chef_client'
  /Users/etagwerker/.rvm/gems/ruby-2.1.2@chef/gems/chef-12.3.0/lib/chef/application.rb:225:in `block in run_chef_client'
  /Users/etagwerker/.rvm/gems/ruby-2.1.2@chef/gems/chef-12.3.0/lib/chef/local_mode.rb:39:in `with_server_connectivity'
  /Users/etagwerker/.rvm/gems/ruby-2.1.2@chef/gems/chef-12.3.0/lib/chef/application.rb:213:in `run_chef_client'
  /Users/etagwerker/.rvm/gems/ruby-2.1.2@chef/gems/chef-12.3.0/lib/chef/application/client.rb:402:in `block in interval_run_chef_client'
  /Users/etagwerker/.rvm/gems/ruby-2.1.2@chef/gems/chef-12.3.0/lib/chef/application/client.rb:392:in `loop'
  /Users/etagwerker/.rvm/gems/ruby-2.1.2@chef/gems/chef-12.3.0/lib/chef/application/client.rb:392:in `interval_run_chef_client'
  /Users/etagwerker/.rvm/gems/ruby-2.1.2@chef/gems/chef-12.3.0/lib/chef/application/client.rb:382:in `run_application'
  /Users/etagwerker/.rvm/gems/ruby-2.1.2@chef/gems/chef-12.3.0/lib/chef/application.rb:60:in `run'
  /Users/etagwerker/.rvm/gems/ruby-2.1.2@chef/gems/chef-12.3.0/bin/chef-client:26:in `<top (required)>'
  /Users/etagwerker/.rvm/gems/ruby-2.1.2@chef/bin/chef-client:23:in `load'
  /Users/etagwerker/.rvm/gems/ruby-2.1.2@chef/bin/chef-client:23:in `<main>'
  /Users/etagwerker/.rvm/gems/ruby-2.1.2@chef/bin/ruby_executable_hooks:15:in `eval'
  /Users/etagwerker/.rvm/gems/ruby-2.1.2@chef/bin/ruby_executable_hooks:15:in `<main>'

Running handlers:
[2015-06-01T17:30:53-03:00] ERROR: Running exception handlers
Running handlers complete
[2015-06-01T17:30:53-03:00] ERROR: Exception handlers complete
[2015-06-01T17:30:53-03:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
[2015-06-01T17:30:53-03:00] DEBUG: Net::HTTPServerException: machine[api] (api::default line 55) had an error: Net::HTTPServerException: chef_node[api] (basic_chef_client::block line 57) had an error: Net::HTTPServerException: 404 "Not Found"
/Users/etagwerker/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/net/http/response.rb:119:in `error!'
/Users/etagwerker/.rvm/gems/ruby-2.1.2@chef/gems/chef-12.3.0/lib/chef/http.rb:145:in `request'
/Users/etagwerker/.rvm/gems/ruby-2.1.2@chef/gems/chef-12.3.0/lib/chef/http.rb:126:in `post'
/Users/etagwerker/.rvm/gems/ruby-2.1.2@chef/gems/cheffish-1.2/lib/chef/provider/chef_node.rb:24:in `block (2 levels) in <class:ChefNode>'
/Users/etagwerker/.rvm/gems/ruby-2.1.2@chef/gems/chef-12.3.0/lib/chef/mixin/why_run.rb:52:in `call'
/Users/etagwerker/.rvm/gems/ruby-2.1.2@chef/gems/chef-12.3.0/lib/chef/mixin/why_run.rb:52:in `add_action'
/Users/etagwerker/.rvm/gems/ruby-2.1.2@chef/gems/chef-12.3.0/lib/chef/provider.rb:165:in `converge_by'
/Users/etagwerker/.rvm/gems/ruby-2.1.2@chef/gems/cheffish-1.2/lib/chef/provider/chef_node.rb:23:in `block in <class:ChefNode>'
/Users/etagwerker/.rvm/gems/ruby-2.1.2@chef/gems/chef-12.3.0/lib/chef/provider/lwrp_base.rb:138:in `instance_eval'
/Users/etagwerker/.rvm/gems/ruby-2.1.2@chef/gems/chef-12.3.0/lib/chef/provider/lwrp_base.rb:138:in `block in action'
/Users/etagwerker/.rvm/gems/ruby-2.1.2@chef/gems/chef-12.3.0/lib/chef/provider.rb:130:in `run_action'
/Users/etagwerker/.rvm/gems/ruby-2.1.2@chef/gems/chef-12.3.0/lib/chef/resource.rb:562:in `run_action'
/Users/etagwerker/.rvm/gems/ruby-2.1.2@chef/gems/chef-12.3.0/lib/chef/runner.rb:49:in `run_action'
/Users/etagwerker/.rvm/gems/ruby-2.1.2@chef/gems/chef-12.3.0/lib/chef/runner.rb:81:in `block (2 levels) in converge'
/Users/etagwerker/.rvm/gems/ruby-2.1.2@chef/gems/chef-12.3.0/lib/chef/runner.rb:81:in `each'
/Users/etagwerker/.rvm/gems/ruby-2.1.2@chef/gems/chef-12.3.0/lib/chef/runner.rb:81:in `block in converge'
/Users/etagwerker/.rvm/gems/ruby-2.1.2@chef/gems/chef-12.3.0/lib/chef/resource_collection/resource_list.rb:83:in `block in execute_each_resource'
/Users/etagwerker/.rvm/gems/ruby-2.1.2@chef/gems/chef-12.3.0/lib/chef/resource_collection/stepable_iterator.rb:116:in `call'
/Users/etagwerker/.rvm/gems/ruby-2.1.2@chef/gems/chef-12.3.0/lib/chef/resource_collection/stepable_iterator.rb:116:in `call_iterator_block'
/Users/etagwerker/.rvm/gems/ruby-2.1.2@chef/gems/chef-12.3.0/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
/Users/etagwerker/.rvm/gems/ruby-2.1.2@chef/gems/chef-12.3.0/lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
/Users/etagwerker/.rvm/gems/ruby-2.1.2@chef/gems/chef-12.3.0/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
/Users/etagwerker/.rvm/gems/ruby-2.1.2@chef/gems/chef-12.3.0/lib/chef/resource_collection/resource_list.rb:81:in `execute_each_resource'
/Users/etagwerker/.rvm/gems/ruby-2.1.2@chef/gems/chef-12.3.0/lib/chef/runner.rb:80:in `converge'
/Users/etagwerker/.rvm/gems/ruby-2.1.2@chef/gems/cheffish-1.2/lib/cheffish/basic_chef_client.rb:69:in `block in converge'
/Users/etagwerker/.rvm/gems/ruby-2.1.2@chef/gems/cheffish-1.2/lib/cheffish/basic_chef_client.rb:133:in `call'
/Users/etagwerker/.rvm/gems/ruby-2.1.2@chef/gems/cheffish-1.2/lib/cheffish/basic_chef_client.rb:133:in `with_chef_config'
/Users/etagwerker/.rvm/gems/ruby-2.1.2@chef/gems/cheffish-1.2/lib/cheffish/basic_chef_client.rb:68:in `converge'
/Users/etagwerker/.rvm/gems/ruby-2.1.2@chef/gems/cheffish-1.2/lib/cheffish/basic_chef_client.rb:109:in `converge_block'
/Users/etagwerker/.rvm/gems/ruby-2.1.2@chef/gems/chef-provisioning-1.2.0/lib/chef/provisioning.rb:12:in `inline_resource'
/Users/etagwerker/.rvm/gems/ruby-2.1.2@chef/gems/chef-provisioning-1.2.0/lib/chef/provisioning/chef_managed_entry_store.rb:55:in `save_data'
/Users/etagwerker/.rvm/gems/ruby-2.1.2@chef/gems/chef-provisioning-1.2.0/lib/chef/provisioning/managed_entry.rb:69:in `save'
/Users/etagwerker/.rvm/gems/ruby-2.1.2@chef/gems/chef-provisioning-1.2.0/lib/chef/provider/machine.rb:33:in `block in <class:Machine>'
/Users/etagwerker/.rvm/gems/ruby-2.1.2@chef/gems/chef-12.3.0/lib/chef/provider/lwrp_base.rb:60:in `instance_eval'
/Users/etagwerker/.rvm/gems/ruby-2.1.2@chef/gems/chef-12.3.0/lib/chef/provider/lwrp_base.rb:60:in `recipe_eval_with_update_check'
/Users/etagwerker/.rvm/gems/ruby-2.1.2@chef/gems/chef-12.3.0/lib/chef/provider/lwrp_base.rb:45:in `block in action'
/Users/etagwerker/.rvm/gems/ruby-2.1.2@chef/gems/chef-provisioning-1.2.0/lib/chef/provider/machine.rb:37:in `block in <class:Machine>'
/Users/etagwerker/.rvm/gems/ruby-2.1.2@chef/gems/chef-12.3.0/lib/chef/provider/lwrp_base.rb:60:in `instance_eval'
/Users/etagwerker/.rvm/gems/ruby-2.1.2@chef/gems/chef-12.3.0/lib/chef/provider/lwrp_base.rb:60:in `recipe_eval_with_update_check'
/Users/etagwerker/.rvm/gems/ruby-2.1.2@chef/gems/chef-12.3.0/lib/chef/provider/lwrp_base.rb:45:in `block in action'
/Users/etagwerker/.rvm/gems/ruby-2.1.2@chef/gems/chef-provisioning-1.2.0/lib/chef/provider/machine.rb:55:in `block in <class:Machine>'
/Users/etagwerker/.rvm/gems/ruby-2.1.2@chef/gems/chef-12.3.0/lib/chef/provider/lwrp_base.rb:60:in `instance_eval'
/Users/etagwerker/.rvm/gems/ruby-2.1.2@chef/gems/chef-12.3.0/lib/chef/provider/lwrp_base.rb:60:in `recipe_eval_with_update_check'
/Users/etagwerker/.rvm/gems/ruby-2.1.2@chef/gems/chef-12.3.0/lib/chef/provider/lwrp_base.rb:45:in `block in action'
/Users/etagwerker/.rvm/gems/ruby-2.1.2@chef/gems/chef-12.3.0/lib/chef/provider.rb:130:in `run_action'
/Users/etagwerker/.rvm/gems/ruby-2.1.2@chef/gems/chef-12.3.0/lib/chef/resource.rb:562:in `run_action'
/Users/etagwerker/.rvm/gems/ruby-2.1.2@chef/gems/chef-12.3.0/lib/chef/runner.rb:49:in `run_action'
/Users/etagwerker/.rvm/gems/ruby-2.1.2@chef/gems/chef-12.3.0/lib/chef/runner.rb:81:in `block (2 levels) in converge'
/Users/etagwerker/.rvm/gems/ruby-2.1.2@chef/gems/chef-12.3.0/lib/chef/runner.rb:81:in `each'
/Users/etagwerker/.rvm/gems/ruby-2.1.2@chef/gems/chef-12.3.0/lib/chef/runner.rb:81:in `block in converge'
/Users/etagwerker/.rvm/gems/ruby-2.1.2@chef/gems/chef-12.3.0/lib/chef/resource_collection/resource_list.rb:83:in `block in execute_each_resource'
/Users/etagwerker/.rvm/gems/ruby-2.1.2@chef/gems/chef-12.3.0/lib/chef/resource_collection/stepable_iterator.rb:116:in `call'
/Users/etagwerker/.rvm/gems/ruby-2.1.2@chef/gems/chef-12.3.0/lib/chef/resource_collection/stepable_iterator.rb:116:in `call_iterator_block'
/Users/etagwerker/.rvm/gems/ruby-2.1.2@chef/gems/chef-12.3.0/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
/Users/etagwerker/.rvm/gems/ruby-2.1.2@chef/gems/chef-12.3.0/lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
/Users/etagwerker/.rvm/gems/ruby-2.1.2@chef/gems/chef-12.3.0/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
/Users/etagwerker/.rvm/gems/ruby-2.1.2@chef/gems/chef-12.3.0/lib/chef/resource_collection/resource_list.rb:81:in `execute_each_resource'
/Users/etagwerker/.rvm/gems/ruby-2.1.2@chef/gems/chef-12.3.0/lib/chef/runner.rb:80:in `converge'
/Users/etagwerker/.rvm/gems/ruby-2.1.2@chef/gems/chef-12.3.0/lib/chef/client.rb:339:in `block in converge'
/Users/etagwerker/.rvm/gems/ruby-2.1.2@chef/gems/chef-12.3.0/lib/chef/client.rb:334:in `catch'
/Users/etagwerker/.rvm/gems/ruby-2.1.2@chef/gems/chef-12.3.0/lib/chef/client.rb:334:in `converge'
/Users/etagwerker/.rvm/gems/ruby-2.1.2@chef/gems/chef-12.3.0/lib/chef/client.rb:353:in `converge_and_save'
/Users/etagwerker/.rvm/gems/ruby-2.1.2@chef/gems/chef-12.3.0/lib/chef/client.rb:457:in `run'
/Users/etagwerker/.rvm/gems/ruby-2.1.2@chef/gems/chef-12.3.0/lib/chef/application.rb:271:in `block in fork_chef_client'
/Users/etagwerker/.rvm/gems/ruby-2.1.2@chef/gems/chef-12.3.0/lib/chef/application.rb:259:in `fork'
/Users/etagwerker/.rvm/gems/ruby-2.1.2@chef/gems/chef-12.3.0/lib/chef/application.rb:259:in `fork_chef_client'
/Users/etagwerker/.rvm/gems/ruby-2.1.2@chef/gems/chef-12.3.0/lib/chef/application.rb:225:in `block in run_chef_client'
/Users/etagwerker/.rvm/gems/ruby-2.1.2@chef/gems/chef-12.3.0/lib/chef/local_mode.rb:39:in `with_server_connectivity'
/Users/etagwerker/.rvm/gems/ruby-2.1.2@chef/gems/chef-12.3.0/lib/chef/application.rb:213:in `run_chef_client'
/Users/etagwerker/.rvm/gems/ruby-2.1.2@chef/gems/chef-12.3.0/lib/chef/application/client.rb:402:in `block in interval_run_chef_client'
/Users/etagwerker/.rvm/gems/ruby-2.1.2@chef/gems/chef-12.3.0/lib/chef/application/client.rb:392:in `loop'
/Users/etagwerker/.rvm/gems/ruby-2.1.2@chef/gems/chef-12.3.0/lib/chef/application/client.rb:392:in `interval_run_chef_client'
/Users/etagwerker/.rvm/gems/ruby-2.1.2@chef/gems/chef-12.3.0/lib/chef/application/client.rb:382:in `run_application'
/Users/etagwerker/.rvm/gems/ruby-2.1.2@chef/gems/chef-12.3.0/lib/chef/application.rb:60:in `run'
/Users/etagwerker/.rvm/gems/ruby-2.1.2@chef/gems/chef-12.3.0/bin/chef-client:26:in `<top (required)>'
/Users/etagwerker/.rvm/gems/ruby-2.1.2@chef/bin/chef-client:23:in `load'
/Users/etagwerker/.rvm/gems/ruby-2.1.2@chef/bin/chef-client:23:in `<main>'
/Users/etagwerker/.rvm/gems/ruby-2.1.2@chef/bin/ruby_executable_hooks:15:in `eval'
/Users/etagwerker/.rvm/gems/ruby-2.1.2@chef/bin/ruby_executable_hooks:15:in `<main>'
Chef Client failed. 0 resources updated in 31.446317 seconds
[2015-06-01T17:30:53-03:00] DEBUG: Server doesn't support resource history, skipping resource report.
[2015-06-01T17:30:53-03:00] DEBUG: Audit Reports are disabled. Skipping sending reports.
[2015-06-01T17:30:53-03:00] ERROR: machine[api] (api::default line 55) had an error: Net::HTTPServerException: chef_node[api] (basic_chef_client::block line 57) had an error: Net::HTTPServerException: 404 "Not Found"
[2015-06-01T17:30:53-03:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

The code does spin up an instance for me, but it doesn't provision it or add the tags that show up in my machine definition. 

Do you know what could be wrong? 

Please let me know.

Thanks!

**Comment by etagwerker** [comment]
After reviewing the logs (/var/log/opscode/nginx/access.log) I noticed that I was getting a 404 for the node queries. It was doing a `GET /nodes/api` instead of a `GET /organizations/ombulabs/nodes/api`

This was very odd because up until the `machine` call everything was working fine. 

It turned out that I had this code in one of my recipes, which was changing the `chef_server_url` to point to the wrong location:

```
with_chef_server "https://chef.ombulabs.com",
  client_name: Chef::Config[:node_name],
  signing_key_filename: Chef::Config[:client_key]
```

I'll leave this here, in case anyone else runs into this issue.
