### ISSUE TITLE
running bundle exec rake rspec fails without a valid /etc/chef/client.pem

### ISSUE THREAD

**Issue by metadave** [chef/chef-provisioning-aws#231]
Without `/etc/chef/client.pem`:

```
bundle exec rspec ./spec/integration/aws_route_table_spec.rb
...

  1) Chef::Resource::AwsRouteTable When the Chef server exists when the chef repo exists and with a VPC with an internet gateway aws_route_table 'test_route_table' with n
o parameters except VPC creates a route table
     Failure/Error: Unable to find matching line from backtrace
     Chef::Exceptions::PrivateKeyMissing:
       I cannot read /etc/chef/client.pem, which you told me to use to sign requests!
     # ./lib/chef/provisioning/aws_driver/aws_resource_with_entry.rb:50:in `get_id_from_managed_entry'
     # ./lib/chef/provisioning/aws_driver/aws_resource_with_entry.rb:90:in `get_driver_and_id'
     # ./lib/chef/provisioning/aws_driver/aws_resource_with_entry.rb:65:in `to_s'
     # ./spec/aws_support.rb:145:in `block (4 levels) in <module:WithAWSClassMethods>'
```

with an *empty* `/etc/chef/client.pem`:

```

  1) Chef::Resource::AwsRouteTable When the Chef server exists when the chef repo exists and with a VPC with an internet gateway aws_route_table 'test_route_table' with no parameters except VPC creates a route table
     Failure/Error: Unable to find matching line from backtrace
     Chef::Exceptions::InvalidPrivateKey:
       The file /etc/chef/client.pem or :raw_key option does not contain a correctly formatted private key.
       The key file should begin with '-----BEGIN RSA PRIVATE KEY-----' and end with '-----END RSA PRIVATE KEY-----'
     # ./lib/chef/provisioning/aws_driver/aws_resource_with_entry.rb:50:in `get_id_from_managed_entry'
     # ./lib/chef/provisioning/aws_driver/aws_resource_with_entry.rb:90:in `get_driver_and_id'
     # ./lib/chef/provisioning/aws_driver/aws_resource_with_entry.rb:65:in `to_s'
     # ./spec/aws_support.rb:145:in `block (4 levels) in <module:WithAWSClassMethods>'
```

**Comment by tyler-ball** [comment]
I was trying to repro this with the latest gems and I was not able to - going to close this for now and we can re-open it if needed
