### ISSUE TITLE
Can not create load_balancer with out machines

### ISSUE THREAD

**Issue by danieljimenez** [chef/chef-provisioning-aws#243]
When attempting to create a load_balancer with no machines, you receive an error saying that either SubnetIDs or Availability Zones must be defined. Seems like possibly a bad nil check.

**Comment by danieljimenez** [comment]
```
  load_balancer "test-public" do
    load_balancer_options subnets: subnets,
                          listeners: [{
                                          instance_port: 8095,
                                          protocol: 'HTTP',
                                          instance_protocol: 'HTTP',
                                          port: 8095
                                      }],
                          attributes: {
                              cross_zone_load_balancing: {
                                  enabled: true
                              }
                          }
  end
```

**Comment by tyler-ball** [comment]
Stacktrace for reference

```
AWS::ELB::Errors::ValidationError: load_balancer[test-public1] (@recipe_files::/Users/tball/chef_repo/cookbooks/test-provisioning/recipes/test.rb line 5) had an error: AWS::ELB::Errors::ValidationError: Either AvailabilityZones or SubnetIds must be specified
/Users/tball/.rvm/gems/ruby-2.1.6@cookbook-test-provisioning/gems/aws-sdk-v1-1.64.0/lib/aws/core/client.rb:375:in `return_or_raise'
/Users/tball/.rvm/gems/ruby-2.1.6@cookbook-test-provisioning/gems/aws-sdk-v1-1.64.0/lib/aws/core/client.rb:476:in `client_request'
(eval):3:in `create_load_balancer'
/Users/tball/.rvm/gems/ruby-2.1.6@cookbook-test-provisioning/gems/aws-sdk-v1-1.64.0/lib/aws/elb/load_balancer_collection.rb:116:in `create'
/Users/tball/github/chef-provisioning-aws/lib/chef/provisioning/aws_driver/driver.rb:95:in `block in allocate_load_balancer'
/Users/tball/.rvm/gems/ruby-2.1.6@cookbook-test-provisioning/gems/chef-12.3.0/lib/chef/mixin/why_run.rb:52:in `call'
/Users/tball/.rvm/gems/ruby-2.1.6@cookbook-test-provisioning/gems/chef-12.3.0/lib/chef/mixin/why_run.rb:52:in `add_action'
/Users/tball/.rvm/gems/ruby-2.1.6@cookbook-test-provisioning/gems/chef-12.3.0/lib/chef/provider.rb:165:in `converge_by'
/Users/tball/github/chef-provisioning/lib/chef/provisioning/chef_provider_action_handler.rb:54:in `perform_action'
/Users/tball/github/chef-provisioning-aws/lib/chef/provisioning/aws_driver/driver.rb:94:in `allocate_load_balancer'
/Users/tball/github/chef-provisioning/lib/chef/provider/load_balancer.rb:34:in `block in <class:LoadBalancer>'
/Users/tball/.rvm/gems/ruby-2.1.6@cookbook-test-provisioning/gems/chef-12.3.0/lib/chef/provider/lwrp_base.rb:138:in `instance_eval'
/Users/tball/.rvm/gems/ruby-2.1.6@cookbook-test-provisioning/gems/chef-12.3.0/lib/chef/provider/lwrp_base.rb:138:in `block in action'
/Users/tball/.rvm/gems/ruby-2.1.6@cookbook-test-provisioning/gems/chef-12.3.0/lib/chef/provider.rb:130:in `run_action'
/Users/tball/.rvm/gems/ruby-2.1.6@cookbook-test-provisioning/gems/chef-12.3.0/lib/chef/resource.rb:562:in `run_action'
/Users/tball/.rvm/gems/ruby-2.1.6@cookbook-test-provisioning/gems/chef-12.3.0/lib/chef/runner.rb:49:in `run_action'
/Users/tball/.rvm/gems/ruby-2.1.6@cookbook-test-provisioning/gems/chef-12.3.0/lib/chef/runner.rb:81:in `block (2 levels) in converge'
/Users/tball/.rvm/gems/ruby-2.1.6@cookbook-test-provisioning/gems/chef-12.3.0/lib/chef/runner.rb:81:in `each'
/Users/tball/.rvm/gems/ruby-2.1.6@cookbook-test-provisioning/gems/chef-12.3.0/lib/chef/runner.rb:81:in `block in converge'
/Users/tball/.rvm/gems/ruby-2.1.6@cookbook-test-provisioning/gems/chef-12.3.0/lib/chef/resource_collection/resource_list.rb:83:in `block in execute_each_resource'
/Users/tball/.rvm/gems/ruby-2.1.6@cookbook-test-provisioning/gems/chef-12.3.0/lib/chef/resource_collection/stepable_iterator.rb:116:in `call'
/Users/tball/.rvm/gems/ruby-2.1.6@cookbook-test-provisioning/gems/chef-12.3.0/lib/chef/resource_collection/stepable_iterator.rb:116:in `call_iterator_block'
/Users/tball/.rvm/gems/ruby-2.1.6@cookbook-test-provisioning/gems/chef-12.3.0/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
/Users/tball/.rvm/gems/ruby-2.1.6@cookbook-test-provisioning/gems/chef-12.3.0/lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
/Users/tball/.rvm/gems/ruby-2.1.6@cookbook-test-provisioning/gems/chef-12.3.0/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
/Users/tball/.rvm/gems/ruby-2.1.6@cookbook-test-provisioning/gems/chef-12.3.0/lib/chef/resource_collection/resource_list.rb:81:in `execute_each_resource'
/Users/tball/.rvm/gems/ruby-2.1.6@cookbook-test-provisioning/gems/chef-12.3.0/lib/chef/runner.rb:80:in `converge'
/Users/tball/.rvm/gems/ruby-2.1.6@cookbook-test-provisioning/gems/chef-12.3.0/lib/chef/client.rb:339:in `block in converge'
/Users/tball/.rvm/gems/ruby-2.1.6@cookbook-test-provisioning/gems/chef-12.3.0/lib/chef/client.rb:334:in `catch'
/Users/tball/.rvm/gems/ruby-2.1.6@cookbook-test-provisioning/gems/chef-12.3.0/lib/chef/client.rb:334:in `converge'
/Users/tball/.rvm/gems/ruby-2.1.6@cookbook-test-provisioning/gems/chef-12.3.0/lib/chef/client.rb:353:in `converge_and_save'
/Users/tball/.rvm/gems/ruby-2.1.6@cookbook-test-provisioning/gems/chef-12.3.0/lib/chef/client.rb:457:in `run'
/Users/tball/.rvm/gems/ruby-2.1.6@cookbook-test-provisioning/gems/chef-12.3.0/lib/chef/application.rb:271:in `block in fork_chef_client'
/Users/tball/.rvm/gems/ruby-2.1.6@cookbook-test-provisioning/gems/chef-12.3.0/lib/chef/application.rb:259:in `fork'
/Users/tball/.rvm/gems/ruby-2.1.6@cookbook-test-provisioning/gems/chef-12.3.0/lib/chef/application.rb:259:in `fork_chef_client'
/Users/tball/.rvm/gems/ruby-2.1.6@cookbook-test-provisioning/gems/chef-12.3.0/lib/chef/application.rb:225:in `block in run_chef_client'
/Users/tball/.rvm/gems/ruby-2.1.6@cookbook-test-provisioning/gems/chef-12.3.0/lib/chef/local_mode.rb:39:in `with_server_connectivity'
/Users/tball/.rvm/gems/ruby-2.1.6@cookbook-test-provisioning/gems/chef-12.3.0/lib/chef/application.rb:213:in `run_chef_client'
/Users/tball/.rvm/gems/ruby-2.1.6@cookbook-test-provisioning/gems/chef-12.3.0/lib/chef/application/client.rb:402:in `block in interval_run_chef_client'
/Users/tball/.rvm/gems/ruby-2.1.6@cookbook-test-provisioning/gems/chef-12.3.0/lib/chef/application/client.rb:392:in `loop'
/Users/tball/.rvm/gems/ruby-2.1.6@cookbook-test-provisioning/gems/chef-12.3.0/lib/chef/application/client.rb:392:in `interval_run_chef_client'
/Users/tball/.rvm/gems/ruby-2.1.6@cookbook-test-provisioning/gems/chef-12.3.0/lib/chef/application/client.rb:382:in `run_application'
/Users/tball/.rvm/gems/ruby-2.1.6@cookbook-test-provisioning/gems/chef-12.3.0/lib/chef/application.rb:60:in `run'
/Users/tball/.rvm/gems/ruby-2.1.6@cookbook-test-provisioning/gems/chef-12.3.0/bin/chef-client:26:in `<top (required)>'
/Users/tball/.rvm/gems/ruby-2.1.6@cookbook-test-provisioning/bin/chef-client:23:in `load'
/Users/tball/.rvm/gems/ruby-2.1.6@cookbook-test-provisioning/bin/chef-client:23:in `<main>'
/Users/tball/.rvm/gems/ruby-2.1.6@cookbook-test-provisioning/bin/ruby_executable_hooks:15:in `eval'
/Users/tball/.rvm/gems/ruby-2.1.6@cookbook-test-provisioning/bin/ruby_executable_hooks:15:in `<main>'%
```

**Comment by tyler-ball** [comment]
The resource declaration `load_balancer "test-public1"` fails - we should update that to succeed by adding default `availability_zones` based upon the region.  http://docs.aws.amazon.com/AWSRubySDK/latest/AWS/ELB/LoadBalancerCollection.html#create-instance_method

**Comment by tyler-ball** [comment]
When using the following recipe:

```ruby
load_balancer "test-public2" do
  load_balancer_options subnets: ['subnet-f16d42b7', 'subnet-0c846869'],
                        listeners: [{
                                        instance_port: 8095,
                                        protocol: 'HTTP',
                                        instance_protocol: 'HTTP',
                                        port: 8095
                                    }],
                        attributes: {
                            cross_zone_load_balancing: {
                                enabled: true
                            }
                        }
end
```

I get the error `  unexpected option attributes` - thats because `attributes` isn't valid to pass during the create.  But if I leave the attributes off, the create succeeds.  

Can you try leaving the attributes off and seeing if your create works?

**Comment by tyler-ball** [comment]
I filed the empty load balancer as another issue - https://github.com/chef/chef-provisioning-aws/issues/244

**Comment by tyler-ball** [comment]
Hey @danieljimenez - were you able to verify that removing `attributes` fixed your issue?

**Comment by tyler-ball** [comment]
I'm going to close this and leave #244 open!
