### ISSUE TITLE
ERROR: bad URI(is not URI?): https://[chef_server_url]/organizations/[organization_name]/data/aws_eip_address/assign eip

### ISSUE THREAD

**Issue by uditjh** [chef/chef-provisioning-aws#257]
```
[2015-07-14T12:38:58-04:00] INFO: Running queued delayed notifications before re-raising exception
[2015-07-14T12:38:58-04:00] DEBUG: Re-raising exception: URI::InvalidURIError - bad URI(is not URI?): https://[chef server url]/organizations/[org name]/data/aws_eip_address/assign eip
/opt/chefdk/embedded/lib/ruby/2.1.0/uri/common.rb:176:in `split'
  /opt/chefdk/embedded/lib/ruby/2.1.0/uri/common.rb:211:in `parse'
  /opt/chefdk/embedded/lib/ruby/2.1.0/uri/common.rb:747:in `parse'
  /opt/chefdk/embedded/apps/chef/lib/chef/http.rb:219:in `create_url'
  /opt/chefdk/embedded/apps/chef/lib/chef/http.rb:140:in `request'
  /opt/chefdk/embedded/apps/chef/lib/chef/http.rb:110:in `get'
  /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-provisioning-1.1.1/lib/chef/provisioning/chef_managed_entry_store.rb:30:in `get_data'
  /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-provisioning-1.1.1/lib/chef/provisioning/managed_entry_store.rb:72:in `get'
  /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-provisioning-aws-1.1.1/lib/chef/provisioning/aws_driver/aws_resource_with_entry.rb:43:in `get_id_from_managed_entry'
  /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-provisioning-aws-1.1.1/lib/chef/provisioning/aws_driver/aws_resource_with_entry.rb:83:in `get_driver_and_id'
  /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-provisioning-aws-1.1.1/lib/chef/provisioning/aws_driver/aws_resource_with_entry.rb:58:in `to_s'
  /opt/chefdk/embedded/apps/chef/lib/chef/formatters/doc.rb:215:in `resource_action_start'
  /opt/chefdk/embedded/apps/chef/lib/chef/event_dispatch/dispatcher.rb:29:in `block (2 levels) in def_forwarding_method'
  /opt/chefdk/embedded/apps/chef/lib/chef/event_dispatch/dispatcher.rb:29:in `each'
  /opt/chefdk/embedded/apps/chef/lib/chef/event_dispatch/dispatcher.rb:29:in `block in def_forwarding_method'
  /opt/chefdk/embedded/apps/chef/lib/chef/resource.rb:540:in `run_action'
  /opt/chefdk/embedded/apps/chef/lib/chef/runner.rb:49:in `run_action'
  /opt/chefdk/embedded/apps/chef/lib/chef/runner.rb:81:in `block (2 levels) in converge'
  /opt/chefdk/embedded/apps/chef/lib/chef/runner.rb:81:in `each'
  /opt/chefdk/embedded/apps/chef/lib/chef/runner.rb:81:in `block in converge'
  /opt/chefdk/embedded/apps/chef/lib/chef/resource_collection/resource_list.rb:83:in `block in execute_each_resource'
  /opt/chefdk/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:116:in `call'
  /opt/chefdk/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:116:in `call_iterator_block'
  /opt/chefdk/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
  /opt/chefdk/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
  /opt/chefdk/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
  /opt/chefdk/embedded/apps/chef/lib/chef/resource_collection/resource_list.rb:81:in `execute_each_resource'
  /opt/chefdk/embedded/apps/chef/lib/chef/runner.rb:80:in `converge'
  /opt/chefdk/embedded/apps/chef/lib/chef/client.rb:339:in `block in converge'
  /opt/chefdk/embedded/apps/chef/lib/chef/client.rb:334:in `catch'
  /opt/chefdk/embedded/apps/chef/lib/chef/client.rb:334:in `converge'
  /opt/chefdk/embedded/apps/chef/lib/chef/client.rb:353:in `converge_and_save'
  /opt/chefdk/embedded/apps/chef/lib/chef/client.rb:457:in `run'
  /opt/chefdk/embedded/apps/chef/lib/chef/application.rb:271:in `block in fork_chef_client'
  /opt/chefdk/embedded/apps/chef/lib/chef/application.rb:259:in `fork'
  /opt/chefdk/embedded/apps/chef/lib/chef/application.rb:259:in `fork_chef_client'
  /opt/chefdk/embedded/apps/chef/lib/chef/application.rb:225:in `block in run_chef_client'
  /opt/chefdk/embedded/apps/chef/lib/chef/local_mode.rb:39:in `with_server_connectivity'
  /opt/chefdk/embedded/apps/chef/lib/chef/application.rb:213:in `run_chef_client'
  /opt/chefdk/embedded/apps/chef/lib/chef/application/client.rb:402:in `block in interval_run_chef_client'
  /opt/chefdk/embedded/apps/chef/lib/chef/application/client.rb:392:in `loop'
  /opt/chefdk/embedded/apps/chef/lib/chef/application/client.rb:392:in `interval_run_chef_client'
  /opt/chefdk/embedded/apps/chef/lib/chef/application/client.rb:382:in `run_application'
  /opt/chefdk/embedded/apps/chef/lib/chef/application.rb:60:in `run'
  /opt/chefdk/embedded/apps/chef/bin/chef-client:26:in `<top (required)>'
  /usr/bin/chef-client:51:in `load'
  /usr/bin/chef-client:51:in `<main>'

Running handlers:
[2015-07-14T12:38:58-04:00] ERROR: Running exception handlers
Running handlers complete
[2015-07-14T12:38:58-04:00] ERROR: Exception handlers complete
[2015-07-14T12:38:58-04:00] INFO: Unable to access cache at /var/chef. Switching cache to /Users/[username]/.chef
[2015-07-14T12:38:58-04:00] INFO: Unable to access cache at /var/chef. Switching cache to /Users/[username]/.chef
[2015-07-14T12:38:58-04:00] FATAL: Stacktrace dumped to /Users/[username]/.chef/cache/chef-stacktrace.out
[2015-07-14T12:38:58-04:00] DEBUG: URI::InvalidURIError: bad URI(is not URI?): https://[chef server]/organizations/[org name]/data/aws_eip_address/assign eip
/opt/chefdk/embedded/lib/ruby/2.1.0/uri/common.rb:176:in `split'
/opt/chefdk/embedded/lib/ruby/2.1.0/uri/common.rb:211:in `parse'
/opt/chefdk/embedded/lib/ruby/2.1.0/uri/common.rb:747:in `parse'
/opt/chefdk/embedded/apps/chef/lib/chef/http.rb:219:in `create_url'
/opt/chefdk/embedded/apps/chef/lib/chef/http.rb:140:in `request'
/opt/chefdk/embedded/apps/chef/lib/chef/http.rb:110:in `get'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-provisioning-1.1.1/lib/chef/provisioning/chef_managed_entry_store.rb:30:in `get_data'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-provisioning-1.1.1/lib/chef/provisioning/managed_entry_store.rb:72:in `get'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-provisioning-aws-1.1.1/lib/chef/provisioning/aws_driver/aws_resource_with_entry.rb:43:in `get_id_from_managed_entry'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-provisioning-aws-1.1.1/lib/chef/provisioning/aws_driver/aws_resource_with_entry.rb:83:in `get_driver_and_id'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-provisioning-aws-1.1.1/lib/chef/provisioning/aws_driver/aws_resource_with_entry.rb:58:in `to_s'
/opt/chefdk/embedded/apps/chef/lib/chef/formatters/doc.rb:215:in `resource_action_start'
/opt/chefdk/embedded/apps/chef/lib/chef/event_dispatch/dispatcher.rb:29:in `block (2 levels) in def_forwarding_method'
/opt/chefdk/embedded/apps/chef/lib/chef/event_dispatch/dispatcher.rb:29:in `each'
/opt/chefdk/embedded/apps/chef/lib/chef/event_dispatch/dispatcher.rb:29:in `block in def_forwarding_method'
/opt/chefdk/embedded/apps/chef/lib/chef/resource.rb:540:in `run_action'
/opt/chefdk/embedded/apps/chef/lib/chef/runner.rb:49:in `run_action'
/opt/chefdk/embedded/apps/chef/lib/chef/runner.rb:81:in `block (2 levels) in converge'
/opt/chefdk/embedded/apps/chef/lib/chef/runner.rb:81:in `each'
/opt/chefdk/embedded/apps/chef/lib/chef/runner.rb:81:in `block in converge'
/opt/chefdk/embedded/apps/chef/lib/chef/resource_collection/resource_list.rb:83:in `block in execute_each_resource'
/opt/chefdk/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:116:in `call'
/opt/chefdk/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:116:in `call_iterator_block'
/opt/chefdk/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
/opt/chefdk/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
/opt/chefdk/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
/opt/chefdk/embedded/apps/chef/lib/chef/resource_collection/resource_list.rb:81:in `execute_each_resource'
/opt/chefdk/embedded/apps/chef/lib/chef/runner.rb:80:in `converge'
/opt/chefdk/embedded/apps/chef/lib/chef/client.rb:339:in `block in converge'
/opt/chefdk/embedded/apps/chef/lib/chef/client.rb:334:in `catch'
/opt/chefdk/embedded/apps/chef/lib/chef/client.rb:334:in `converge'
/opt/chefdk/embedded/apps/chef/lib/chef/client.rb:353:in `converge_and_save'
/opt/chefdk/embedded/apps/chef/lib/chef/client.rb:457:in `run'
/opt/chefdk/embedded/apps/chef/lib/chef/application.rb:271:in `block in fork_chef_client'
/opt/chefdk/embedded/apps/chef/lib/chef/application.rb:259:in `fork'
/opt/chefdk/embedded/apps/chef/lib/chef/application.rb:259:in `fork_chef_client'
/opt/chefdk/embedded/apps/chef/lib/chef/application.rb:225:in `block in run_chef_client'
/opt/chefdk/embedded/apps/chef/lib/chef/local_mode.rb:39:in `with_server_connectivity'
/opt/chefdk/embedded/apps/chef/lib/chef/application.rb:213:in `run_chef_client'
/opt/chefdk/embedded/apps/chef/lib/chef/application/client.rb:402:in `block in interval_run_chef_client'
/opt/chefdk/embedded/apps/chef/lib/chef/application/client.rb:392:in `loop'
/opt/chefdk/embedded/apps/chef/lib/chef/application/client.rb:392:in `interval_run_chef_client'
/opt/chefdk/embedded/apps/chef/lib/chef/application/client.rb:382:in `run_application'
/opt/chefdk/embedded/apps/chef/lib/chef/application.rb:60:in `run'
/opt/chefdk/embedded/apps/chef/bin/chef-client:26:in `<top (required)>'
/usr/bin/chef-client:51:in `load'
/usr/bin/chef-client:51:in `<main>'
Chef Client failed. 1 resources updated in 126.085191 seconds
```

**Comment by lynchc** [comment]
Can you post your recipe? What were you trying to do?

**Comment by uditjh** [comment]
require 'chef/resource/aws_vpc'
require 'chef/provisioning/aws_driver'
with_driver 'aws'

node.default[:machine][:image_id] = "ami-b18c62da"      
node.default[:machine][:instance_type] = "m3.medium"
node.default[:machine][:ssh_username] = "ec2-user"

machine_options = {
  :bootstrap_options => {
     :key_name => 'chef_infra',
     :instance_type => node[:machine][:instance_type],
     :subnet_id => 'subnet-524fa70b',
     :security_group_ids => ['sg-21dd9744','sg-8182ade5','sg-6b6b240f','sg-7aed241d']
  },
  :image_id => node[:machine][:image_id],
  :ssh_username => node[:machine][:ssh_username]
}

machine 'jenkins-master' do
  machine_options machine_options
  converge true
  role 'jenkins-master'
  action node[:machine][:action]
end

aws_eip_address 'assign eip' do
  machine 'jenkins-master'
  associate_to_vpc true
  public_ip 'XX.XX.XX.XX'
end

**Comment by tyler-ball** [comment]
@uditjh Did you copy the `public_ip` attribute out of the console?  It must be an IP they assign you.

Also, can you try this using the ChefDK 0.7.0?  It has some later versions of chef-provisioning and chef-provisioning-aws that may have fixed this issue.

**Comment by tyler-ball** [comment]
Hey @uditjh - we haven't heard back from you in a while, so I'm going to close this.  Please re-open if you're experiencing issues using the latest ChefDK!
