### ISSUE TITLE
Intermittent AWS AuthFailure executing aws_key_pair

### ISSUE THREAD

**Issue by patrick-wright** [chef/chef-provisioning-aws#268]
Ive been seeing this error about 30% of the time in Delivery.  I'm not sure whether this is an issue with the resource or network related with Delivery and AWS.  I figure I would document this here if some one can take a look at it.  Perhaps retry logic would be an option?  What do you think @tyler-ball?

```
* aws_key_pair[qa-chef-server-cluster-default] action create[2015-07-29T16:05:35+00:00] WARN: Class Chef::Provider::AwsKeyPair does not declare 'resource_name :aws_key_pair'.
[2015-07-29T16:05:35+00:00] WARN: This will no longer work in Chef 13: you must use 'resource_name' to provide DSL.

================================================================================
    Error executing action `create` on resource 'aws_key_pair[qa-chef-server-cluster-default]'
    ================================================================================
    
    AWS::EC2::Errors::AuthFailure
    -----------------------------
    AWS was not able to validate the provided access credentials
    
    Resource Declaration:
    ---------------------
    # In /var/opt/delivery/workspace/delivery.chef.co/chef/chef-server/chef-server-acceptance/ha_upgrade_aws/acceptance/provision/repo/deps/qa-chef-server-cluster/.chef/local-mode-cache/cache/cookbooks/qa-chef-server-cluster/recipes/provisioner-setup.rb
    
     61: aws_key_pair node['qa-chef-server-cluster']['aws']['machine_options']['bootstrap_options']['key_name'] do
     62:   private_key_path priv_key
     63:   public_key_path pub_key
     64:   allow_overwrite true
     65: end
     66: 
    
    Compiled Resource:
    ------------------
    # Declared in /var/opt/delivery/workspace/delivery.chef.co/chef/chef-server/chef-server-acceptance/ha_upgrade_aws/acceptance/provision/repo/deps/qa-chef-server-cluster/.chef/local-mode-cache/cache/cookbooks/qa-chef-server-cluster/recipes/provisioner-setup.rb:61:in `from_file'
    
    aws_key_pair("qa-chef-server-cluster-default") do
      action [:create]
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      driver #false, :force_formatter=>true, :color=>true, :local_mode=>true, :pid_file=>"10257", 
      ...
```

**Comment by tyler-ball** [comment]
@patrick-wright can you grab the full stacktrace?  We're probably going to have to add some debug logging and repro to figure out whats up.

**Comment by patrick-wright** [comment]
```
Generated at 2015-07-31 19:38:03 +0000
AWS::EC2::Errors::AuthFailure: aws_key_pair[qa-chef-server-cluster-default] (qa-chef-server-cluster::provisioner-setup line 61) had an error: AWS::EC2::Errors::AuthFailure: AWS was not able to validate the provided access credentials
/var/opt/delivery/workspace/delivery.chef.co/chef/chef-server/chef-server-acceptance/project_gem_cache/ruby/2.1.0/gems/aws-sdk-v1-1.64.0/lib/aws/core/client.rb:375:in `return_or_raise'
/var/opt/delivery/workspace/delivery.chef.co/chef/chef-server/chef-server-acceptance/project_gem_cache/ruby/2.1.0/gems/aws-sdk-v1-1.64.0/lib/aws/core/client.rb:476:in `client_request'
(eval):3:in `describe_key_pairs'
/var/opt/delivery/workspace/delivery.chef.co/chef/chef-server/chef-server-acceptance/project_gem_cache/ruby/2.1.0/gems/aws-sdk-v1-1.64.0/lib/aws/ec2/key_pair.rb:43:in `exists?'
/var/opt/delivery/workspace/delivery.chef.co/chef/chef-server/chef-server-acceptance/project_gem_cache/ruby/2.1.0/bundler/gems/chef-provisioning-aws-205e3c20a485/lib/chef/resource/aws_key_pair.rb:18:in `aws_object'
/var/opt/delivery/workspace/delivery.chef.co/chef/chef-server/chef-server-acceptance/project_gem_cache/ruby/2.1.0/bundler/gems/chef-provisioning-aws-205e3c20a485/lib/chef/provider/aws_key_pair.rb:169:in `load_current_resource'
/var/opt/delivery/workspace/delivery.chef.co/chef/chef-server/chef-server-acceptance/project_gem_cache/ruby/2.1.0/gems/chef-12.4.1/lib/chef/provider.rb:123:in `run_action'
/var/opt/delivery/workspace/delivery.chef.co/chef/chef-server/chef-server-acceptance/project_gem_cache/ruby/2.1.0/gems/chef-12.4.1/lib/chef/resource.rb:584:in `run_action'
/var/opt/delivery/workspace/delivery.chef.co/chef/chef-server/chef-server-acceptance/project_gem_cache/ruby/2.1.0/gems/chef-12.4.1/lib/chef/runner.rb:49:in `run_action'
/var/opt/delivery/workspace/delivery.chef.co/chef/chef-server/chef-server-acceptance/project_gem_cache/ruby/2.1.0/gems/chef-12.4.1/lib/chef/runner.rb:81:in `block (2 levels) in converge'
/var/opt/delivery/workspace/delivery.chef.co/chef/chef-server/chef-server-acceptance/project_gem_cache/ruby/2.1.0/gems/chef-12.4.1/lib/chef/runner.rb:81:in `each'
/var/opt/delivery/workspace/delivery.chef.co/chef/chef-server/chef-server-acceptance/project_gem_cache/ruby/2.1.0/gems/chef-12.4.1/lib/chef/runner.rb:81:in `block in converge'
/var/opt/delivery/workspace/delivery.chef.co/chef/chef-server/chef-server-acceptance/project_gem_cache/ruby/2.1.0/gems/chef-12.4.1/lib/chef/resource_collection/resource_list.rb:83:in `block in execute_each_resource'
/var/opt/delivery/workspace/delivery.chef.co/chef/chef-server/chef-server-acceptance/project_gem_cache/ruby/2.1.0/gems/chef-12.4.1/lib/chef/resource_collection/stepable_iterator.rb:116:in `call'
/var/opt/delivery/workspace/delivery.chef.co/chef/chef-server/chef-server-acceptance/project_gem_cache/ruby/2.1.0/gems/chef-12.4.1/lib/chef/resource_collection/stepable_iterator.rb:116:in `call_iterator_block'
/var/opt/delivery/workspace/delivery.chef.co/chef/chef-server/chef-server-acceptance/project_gem_cache/ruby/2.1.0/gems/chef-12.4.1/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
/var/opt/delivery/workspace/delivery.chef.co/chef/chef-server/chef-server-acceptance/project_gem_cache/ruby/2.1.0/gems/chef-12.4.1/lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
/var/opt/delivery/workspace/delivery.chef.co/chef/chef-server/chef-server-acceptance/project_gem_cache/ruby/2.1.0/gems/chef-12.4.1/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
/var/opt/delivery/workspace/delivery.chef.co/chef/chef-server/chef-server-acceptance/project_gem_cache/ruby/2.1.0/gems/chef-12.4.1/lib/chef/resource_collection/resource_list.rb:81:in `execute_each_resource'
/var/opt/delivery/workspace/delivery.chef.co/chef/chef-server/chef-server-acceptance/project_gem_cache/ruby/2.1.0/gems/chef-12.4.1/lib/chef/runner.rb:80:in `converge'
/var/opt/delivery/workspace/delivery.chef.co/chef/chef-server/chef-server-acceptance/project_gem_cache/ruby/2.1.0/gems/chef-12.4.1/lib/chef/client.rb:654:in `block in converge'
/var/opt/delivery/workspace/delivery.chef.co/chef/chef-server/chef-server-acceptance/project_gem_cache/ruby/2.1.0/gems/chef-12.4.1/lib/chef/client.rb:649:in `catch'
/var/opt/delivery/workspace/delivery.chef.co/chef/chef-server/chef-server-acceptance/project_gem_cache/ruby/2.1.0/gems/chef-12.4.1/lib/chef/client.rb:649:in `converge'
/var/opt/delivery/workspace/delivery.chef.co/chef/chef-server/chef-server-acceptance/project_gem_cache/ruby/2.1.0/gems/chef-12.4.1/lib/chef/client.rb:688:in `converge_and_save'
/var/opt/delivery/workspace/delivery.chef.co/chef/chef-server/chef-server-acceptance/project_gem_cache/ruby/2.1.0/gems/chef-12.4.1/lib/chef/client.rb:269:in `run'
/var/opt/delivery/workspace/delivery.chef.co/chef/chef-server/chef-server-acceptance/project_gem_cache/ruby/2.1.0/gems/chef-12.4.1/lib/chef/application.rb:270:in `block in fork_chef_client'
/var/opt/delivery/workspace/delivery.chef.co/chef/chef-server/chef-server-acceptance/project_gem_cache/ruby/2.1.0/gems/chef-12.4.1/lib/chef/application.rb:258:in `fork'
/var/opt/delivery/workspace/delivery.chef.co/chef/chef-server/chef-server-acceptance/project_gem_cache/ruby/2.1.0/gems/chef-12.4.1/lib/chef/application.rb:258:in `fork_chef_client'
/var/opt/delivery/workspace/delivery.chef.co/chef/chef-server/chef-server-acceptance/project_gem_cache/ruby/2.1.0/gems/chef-12.4.1/lib/chef/application.rb:224:in `block in run_chef_client'
/var/opt/delivery/workspace/delivery.chef.co/chef/chef-server/chef-server-acceptance/project_gem_cache/ruby/2.1.0/gems/chef-12.4.1/lib/chef/local_mode.rb:39:in `with_server_connectivity'
/var/opt/delivery/workspace/delivery.chef.co/chef/chef-server/chef-server-acceptance/project_gem_cache/ruby/2.1.0/gems/chef-12.4.1/lib/chef/application.rb:212:in `run_chef_client'
/var/opt/delivery/workspace/delivery.chef.co/chef/chef-server/chef-server-acceptance/project_gem_cache/ruby/2.1.0/gems/chef-12.4.1/lib/chef/application/client.rb:402:in `block in interval_run_chef_client'
/var/opt/delivery/workspace/delivery.chef.co/chef/chef-server/chef-server-acceptance/project_gem_cache/ruby/2.1.0/gems/chef-12.4.1/lib/chef/application/client.rb:392:in `loop'
/var/opt/delivery/workspace/delivery.chef.co/chef/chef-server/chef-server-acceptance/project_gem_cache/ruby/2.1.0/gems/chef-12.4.1/lib/chef/application/client.rb:392:in `interval_run_chef_client'
/var/opt/delivery/workspace/delivery.chef.co/chef/chef-server/chef-server-acceptance/project_gem_cache/ruby/2.1.0/gems/chef-12.4.1/lib/chef/application/client.rb:382:in `run_application'
/var/opt/delivery/workspace/delivery.chef.co/chef/chef-server/chef-server-acceptance/project_gem_cache/ruby/2.1.0/gems/chef-12.4.1/lib/chef/application.rb:60:in `run'
/var/opt/delivery/workspace/delivery.chef.co/chef/chef-server/chef-server-acceptance/project_gem_cache/ruby/2.1.0/gems/chef-12.4.1/bin/chef-client:26:in `<top (required)>'
/var/opt/delivery/workspace/delivery.chef.co/chef/chef-server/chef-server-acceptance/project_gem_cache/ruby/2.1.0/bin/chef-client:23:in `load'
/var/opt/delivery/workspace/delivery.chef.co/chef/chef-server/chef-server-acceptance/project_gem_cache/ruby/2.1.0/bin/chef-client:23:in `<main>'root@ip-10-194-15-105:/var/opt/delivery/workspace/delivery.chef.co/chef/chef-server/chef-server-acceptance/standalone_upgrade_aw
```

**Comment by tyler-ball** [comment]
Is it always the `aws_key_pair` resource that fails?

**Comment by patrick-wright** [comment]
Yes, it's the first chef-provisioning-aws resource that gets executed.

**Comment by cwebberOps** [comment]
I am seeing this as well. It is interesting to note that it always seems to happen in Deploy and not Provision. It is almost as if we are hitting an api limit threshold...

**Comment by patrick-wright** [comment]
We discovered this error was only occurring on a few nodes in Delivery.  They have been rebuilt and we have not seen this error since.

**Comment by tyler-ball** [comment]
Yayyyyyy!  Let me know if they start showing back up.

**Comment by dushyant28** [comment]
I am facing this issue on a provisioning node (on AWS). Is there any way i can fix this without creating a new node ?
