### ISSUE TITLE
associate_public_ip_address no longer working

### ISSUE THREAD

**Issue by tyler-ball** [chef/chef-provisioning-aws#338]
\cc @cwebberOps 

```
Generated at 2015-09-22 03:42:31 +0000
ArgumentError: machine_batch[default] (build-cookbook::provision line 78) had an error: ArgumentError: unexpected value at params[:associate_public_ip_address]
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.1.23/lib/aws-sdk-core/param_validator.rb:26:in `validate!'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.1.23/lib/aws-sdk-core/param_validator.rb:11:in `validate!'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.1.23/lib/aws-sdk-core/plugins/param_validator.rb:20:in `call'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.1.23/lib/aws-sdk-core/plugins/logging.rb:39:in `call'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.1.23/lib/seahorse/client/plugins/raise_response_errors.rb:14:in `call'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.1.23/lib/aws-sdk-core/plugins/param_converter.rb:21:in `call'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.1.23/lib/seahorse/client/plugins/response_target.rb:21:in `call'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.1.23/lib/seahorse/client/request.rb:70:in `send_request'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.1.23/lib/seahorse/client/base.rb:207:in `block (2 levels) in define_operation_methods'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-resources-2.1.23/lib/aws-sdk-resources/request.rb:24:in `call'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-resources-2.1.23/lib/aws-sdk-resources/operations.rb:41:in `call'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-resources-2.1.23/lib/aws-sdk-resources/operations.rb:87:in `call'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-resources-2.1.23/lib/aws-sdk-resources/operation_methods.rb:19:in `block in add_operation'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-provisioning-aws-1.4.0/lib/chef/provisioning/aws_driver/driver.rb:1132:in `create_instance_and_reference'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-provisioning-aws-1.4.0/lib/chef/provisioning/aws_driver/driver.rb:1096:in `block (2 levels) in create_servers'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.4.2/lib/chef/chef_fs/parallelizer/parallel_enumerable.rb:267:in `call'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.4.2/lib/chef/chef_fs/parallelizer/parallel_enumerable.rb:267:in `process_input'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.4.2/lib/chef/chef_fs/parallelizer/parallel_enumerable.rb:257:in `process_one'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.4.2/lib/chef/chef_fs/parallelizer.rb:93:in `call'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.4.2/lib/chef/chef_fs/parallelizer.rb:93:in `worker_loop'
```

**Comment by cwebberOps** [comment]
```
    {
      ssh_username: 'ubuntu',
      location: availability_zone(region, instance_num),
      convergence_options: {
        chef_config_text: "encrypted_data_bag_secret File.join(File.dirname(__FILE__), 'encrypted_data_bag_secret')"
      },
      use_private_ip_for_ssh: true,
      bootstrap_options: {
        image_id: image_id(node),
        instance_type: instance_type(node),
        subnet_id: subnet_id(node, availability_zone(region, instance_num), public_network),
        security_group_ids: security_groups(node, region),
        key_name: project_name(node),
        network_interfaces: [
          { associate_public_ip_address: true }
        ]
      },
      aws_tags: { 'X-Project' => project_name(node), 'X-Contact' => '#cia' }
    }
```

So when I call it like above it blows up with:
```
  * machine[speakr-acceptance] action setup
    
    ================================================================================
    Error executing action `setup` on resource 'machine[speakr-acceptance]'
    ================================================================================
    
    Chef::Exceptions::ValidationFailed
    ----------------------------------
    Option name must be a kind of String!  You passed {:associate_public_ip_address=>true}.
    
```

**Comment by cwebberOps** [comment]
Original config:
```
    {
      ssh_username: 'ubuntu',
      location: availability_zone(region, instance_num),
      convergence_options: {
        chef_config_text: "encrypted_data_bag_secret File.join(File.dirname(__FILE__), 'encrypted_data_bag_secret')"
      },
      use_private_ip_for_ssh: true,
      bootstrap_options: {
        image_id: image_id(node),
        instance_type: instance_type(node),
        subnet_id: subnet_id(node, availability_zone(region, instance_num), public_network),
        security_group_ids: security_groups(node, region),
        associate_public_ip_address: public_network,
        key_name: project_name(node)
      },
      aws_tags: { 'X-Project' => project_name(node), 'X-Contact' => '#cia' }
    }
```

**Comment by tyler-ball** [comment]
> Option name must be a kind of string!

Is https://github.com/chef/chef-provisioning-aws/issues/322
