### ISSUE TITLE
Error updating Route Table to use a machine as gateway

### ISSUE THREAD

**Issue by lfrodrigues** [chef/chef-provisioning-aws#353]
I created a machine using machine and want to set one of my route tables as follows:
```
aws_route_table 'route-table-management' do
    vpc 'vpc-my'
    routes '0.0.0.0/0' => 'i-dd01ef7f'
    aws_tags :chef_type => "aws_route_table"
end
```

In 'i-dd01ef7f' I also tried the machine name but I get same error:
```
uninitialized constant Aws::EC2::AwsVpcPeeringConnection
```

Am I doing something wrong or is this a bug?

**Comment by tyler-ball** [comment]
@lfrodrigues Well that doesn't seem right - are you using the latest version of the ChefDK?  At the end of you chef run you should see a message about a stacktrace - can you find that file and include it here?

**Comment by lfrodrigues** [comment]
Using chef-dk 0.8.1. I saw 0.9.0 in git's changelog but no release so I guess this is the most recent?

Here's the file, github did not let me attach it...
```
Generated at 2015-10-06 20:53:30 +0000
NameError: aws_route_table[route-table-VPN-external] (rtb-1eee697a) (cluster_phase2::machine_ipsec line 80) had an error: NameError: uninitialized constant Aws::EC2::AwsVpcPeeringConnection
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-provisioning-aws-1.4.1/lib/chef/provider/aws_route_table.rb:144:in `get_route_target'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-provisioning-aws-1.4.1/lib/chef/provider/aws_route_table.rb:83:in `block in update_routes'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-provisioning-aws-1.4.1/lib/chef/provider/aws_route_table.rb:82:in `each'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-provisioning-aws-1.4.1/lib/chef/provider/aws_route_table.rb:82:in `update_routes'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-provisioning-aws-1.4.1/lib/chef/provider/aws_route_table.rb:13:in `action_create'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.4.4/lib/chef/provider.rb:140:in `run_action'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.4.4/lib/chef/resource.rb:584:in `run_action'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.4.4/lib/chef/runner.rb:49:in `run_action'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.4.4/lib/chef/runner.rb:81:in `block (2 levels) in converge'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.4.4/lib/chef/runner.rb:81:in `each'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.4.4/lib/chef/runner.rb:81:in `block in converge'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.4.4/lib/chef/resource_collection/resource_list.rb:83:in `block in execute_each_resource'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.4.4/lib/chef/resource_collection/stepable_iterator.rb:116:in `call'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.4.4/lib/chef/resource_collection/stepable_iterator.rb:116:in `call_iterator_block'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.4.4/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.4.4/lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.4.4/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.4.4/lib/chef/resource_collection/resource_list.rb:81:in `execute_each_resource'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.4.4/lib/chef/runner.rb:80:in `converge'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.4.4/lib/chef/client.rb:654:in `block in converge'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.4.4/lib/chef/client.rb:649:in `catch'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.4.4/lib/chef/client.rb:649:in `converge'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.4.4/lib/chef/client.rb:688:in `converge_and_save'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.4.4/lib/chef/client.rb:269:in `run'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.4.4/lib/chef/application.rb:270:in `block in fork_chef_client'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.4.4/lib/chef/application.rb:258:in `fork'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.4.4/lib/chef/application.rb:258:in `fork_chef_client'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.4.4/lib/chef/application.rb:224:in `block in run_chef_client'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.4.4/lib/chef/local_mode.rb:39:in `with_server_connectivity'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.4.4/lib/chef/application.rb:212:in `run_chef_client'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.4.4/lib/chef/application/client.rb:402:in `block in interval_run_chef_client'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.4.4/lib/chef/application/client.rb:392:in `loop'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.4.4/lib/chef/application/client.rb:392:in `interval_run_chef_client'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.4.4/lib/chef/application/client.rb:382:in `run_application'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.4.4/lib/chef/application.rb:60:in `run'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.4.4/bin/chef-client:26:in `<top (required)>'
/usr/bin/chef-client:54:in `load'
/usr/bin/chef-client:54:in `<main>'
```

**Comment by lskillen** [comment]
@lfrodrigues This [seems to be fixed](https://github.com/chef/chef-provisioning-aws/blob/ab76b49da4b474dca3a86326bce268416e74cfc7/lib/chef/provider/aws_route_table.rb#L145-L146) (see link for code) in the master branch of chef-provisioning-aws - The constant name was [previously](https://github.com/chef/chef-provisioning-aws/blob/02b804daa12fbe752ef66701319f2f35347ffcb9/lib/chef/provider/aws_route_table.rb#L144-L145) (as of v1.4.1) specified as `::Aws::EC2::AwsVpcPeeringConnection` instead of `::Aws::EC2::VpcPeeringConnection` (note the extra `Aws` in the former).  Your options are to wait until the next release or use the gem directly from github in the meantime.  For the latter you can do something like (YMMV):

```
gem install specific_install
gem specific_install -l https://github.com/chef/chef-provisioning-aws
```

HTH. :smile:

**Comment by lfrodrigues** [comment]
@lskillen thanks for the info! 
Hopefully a new release won't be far in future.

**Comment by tyler-ball** [comment]
I'm going to close this because it is fixed in master - 1.5.0 is coming out this week or next!

**Comment by lfrodrigues** [comment]
I still get an error using 1.5.1

```
undefined method `target' for #<Aws::EC2::Route:0x0000000933c0f8>
```

```
Generated at 2015-10-14 15:20:31 +0000
NoMethodError: aws_route_table[route-table-management] (rtb-1d7d2a78) (cluster_phase1::machine_internetnat line 55) had an error: NoMethodError: undefined method `target' for #<Aws::EC2::Route:0x00000
00caf0210>
/home/ubuntu/.chefdk/gem/ruby/2.1.0/gems/chef-provisioning-aws-1.5.1/lib/chef/provider/aws_route_table.rb:90:in `block in update_routes'
/home/ubuntu/.chefdk/gem/ruby/2.1.0/gems/chef-provisioning-aws-1.5.1/lib/chef/provider/aws_route_table.rb:82:in `each'
/home/ubuntu/.chefdk/gem/ruby/2.1.0/gems/chef-provisioning-aws-1.5.1/lib/chef/provider/aws_route_table.rb:82:in `update_routes'
/home/ubuntu/.chefdk/gem/ruby/2.1.0/gems/chef-provisioning-aws-1.5.1/lib/chef/provider/aws_route_table.rb:13:in `action_create'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/provider.rb:144:in `run_action'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/resource.rb:585:in `run_action'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/runner.rb:49:in `run_action'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/runner.rb:81:in `block (2 levels) in converge'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/runner.rb:81:in `each'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/runner.rb:81:in `block in converge'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/resource_collection/resource_list.rb:83:in `block in execute_each_resource'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/resource_collection/stepable_iterator.rb:116:in `call'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/resource_collection/stepable_iterator.rb:116:in `call_iterator_block'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/resource_collection/resource_list.rb:81:in `execute_each_resource'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/runner.rb:80:in `converge'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/client.rb:653:in `block in converge'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/client.rb:648:in `catch'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/client.rb:648:in `converge'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/client.rb:687:in `converge_and_save'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/client.rb:269:in `run'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/application.rb:270:in `block in fork_chef_client'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/application.rb:258:in `fork'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/application.rb:258:in `fork_chef_client'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/application.rb:224:in `block in run_chef_client'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/local_mode.rb:44:in `with_server_connectivity'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/application.rb:212:in `run_chef_client'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/application/client.rb:408:in `block in interval_run_chef_client'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/application/client.rb:398:in `loop'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/application/client.rb:398:in `interval_run_chef_client'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/application/client.rb:388:in `run_application'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/application.rb:60:in `run'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/bin/chef-client:26:in `<top (required)>'
/usr/bin/chef-client:54:in `load'
/usr/bin/chef-client:54:in `<main>'
```

**Comment by lskillen** [comment]
It seems like [this line](https://github.com/chef/chef-provisioning-aws/blob/204a11111b44b1cb2bcfb25fb180974d40d6b1e8/lib/chef/provider/aws_route_table.rb#L90) should reference `current_target` instead of `current_route.target` (AWS::EC2::Route doesn't have a `target` attribute or method, not sure if this existing previously).  This seems to happen when the route you are setting differs from what is there, so a quick fix might be to remove it or change it in the AWS console first before converging.

As an aside, I've also seen a *similar* error in this area, except it happened when I had an existing VPC Endpointto S3  in the route table, which doesn't seem to be supported yet at the SDK level (other than it being a different identifier string).  It caused the current_route to be nil because it wasn't one of the identifiers looked.

**Comment by lfrodrigues** [comment]
I realized I can update in in console but that kind of defeats  the purpose of using chef ;) 

I didn't fully understand you comment, is this a bug in provisioning-aws or in AWS SDK?

**Comment by lfrodrigues** [comment]
I guess related to this found another problem. I have:
```
aws_route_table 'route-table-VPN-external' do
    vpc 'vpc-my'
    routes '0.0.0.0/0' => 'internet-nat-1'
    routes '10.140.111.0/24' => 'ipsec-1'
    aws_tags :chef_type => "aws_route_table"
end
```

It should add 2 routes to my route table but it doesn't. Only adds the second and local.
If I add  '0.0.0.0/0' manually in console next time chef runs it deletes it. 

```
[2015-10-14T16:54:43+00:00] INFO: [Aws::EC2::Client 200 0.072556 0 retries] delete_route(route_table_id:"rtb-627c2b07",destination_cidr_block:"0.0.0.0/0")  
- remove route sending 0.0.0.0/0 to i-f4bcd94d
```

**Comment by lskillen** [comment]
Absolutely I agree it shouldn't be manual! ;-)

But short-term workarounds are acceptable when the guys are doing an awesome job of turning around fixes so quickly (just a note, I'm not a contributor to chef-provisioning-aws [yet], just another user who's been investing quite a bit of time into learning Chef provisioning recently!)

Your bug is a bug in chef-provisioning-aws (in your specific case anyway), but there's also other issues associated with route table functionality that is missing in both the AWS Ruby SDK and chef-provisioning-aws.

As for the resource you've mentioned the `routes` attribute/property isn't additive, it takes a hash, so you should be putting them all into one as such:

```
aws_route_table 'route-table-VPN-external' do
    vpc 'vpc-my'
    routes(
       '0.0.0.0/0' => 'internet-nat-1',
       '10.140.111.0/24' => 'ipsec-1'
    )
    aws_tags :chef_type => "aws_route_table"
end
```

HTH! :-)

**Comment by lfrodrigues** [comment]
True, the support in chef-provision-aws is awesome! I'm using the workaround, whenever it get's fixed I'll uncomment the code :)

Thanks for the help @lskillen, I completely missed that one.

**Comment by lskillen** [comment]
You're welcome!  I also created a new issue for the bug we spoke about above: #367
