### ISSUE TITLE
Bug when changing existing routes on aws_route_table converge

### ISSUE THREAD

**Issue by lskillen** [chef/chef-provisioning-aws#367]
Referencing #353, @lfrodrigues encountered a bug in v.1.5.1 when converging an aws_route_table that was replacing an existing route (see #353 for the full backtrace).

```
undefined method `target' for #<Aws::EC2::Route:0x0000000933c0f8>
```

```
NoMethodError: aws_route_table[route-table-management] (rtb-1d7d2a78) (cluster_phase1::machine_internetnat line 55) had an error: NoMethodError: undefined method `target' for #<Aws::EC2::Route:0x00000
00caf0210>
```

My analysis was:

> It seems like this line should reference current_target instead of current_route.target (AWS::EC2::Route doesn't have a target attribute or method, not sure if this existing previously). This seems to happen when the route you are setting differs from what is there, so a quick fix might be to remove it or change it in the AWS console first before converging.

**Comment by josb** [comment]
I'm running into this problem as well, and I changed the code to use ```current_target``` as @lskillen suggests (thanks!). This fixes the issue here.

**Comment by lfrodrigues** [comment]
Hey, I still have same error in version 1.6.1:

```
Generated at 2015-11-18 14:09:10 +0000
NoMethodError: aws_route_table[route-table-cc-backend-test] (rtb-12416177) (network::luis line 2) had an error: NoMethodError: undefined method `target' for #<Aws::EC2::Route:0x0000000d250c80>
/home/ubuntu/.chefdk/gem/ruby/2.1.0/gems/chef-provisioning-aws-1.6.1/lib/chef/provider/aws_route_table.rb:90:in `block in update_routes'
/home/ubuntu/.chefdk/gem/ruby/2.1.0/gems/chef-provisioning-aws-1.6.1/lib/chef/provider/aws_route_table.rb:82:in `each'
/home/ubuntu/.chefdk/gem/ruby/2.1.0/gems/chef-provisioning-aws-1.6.1/lib/chef/provider/aws_route_table.rb:82:in `update_routes'
/home/ubuntu/.chefdk/gem/ruby/2.1.0/gems/chef-provisioning-aws-1.6.1/lib/chef/provider/aws_route_table.rb:13:in `action_create'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/provider.rb:144:in `run_action'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/resource.rb:585:in `run_action'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/runner.rb:49:in `run_action'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/runner.rb:81:in `block (2 levels) in converge'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/runner.rb:81:in `each'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/runner.rb:81:in `block in converge'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/resource_collection/resource_list.rb:83:in `block in execute_each_resource'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/resource_collection/stepable_iterator.rb:116:in `call'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/resource_collection/stepable_iterator.rb:116:in `call_iterator_block'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/resource_collection/resource_list.rb:81:in `execute_each_resource'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/runner.rb:80:in `converge'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/client.rb:653:in `block in converge'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/client.rb:648:in `catch'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/client.rb:648:in `converge'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/client.rb:687:in `converge_and_save'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/client.rb:269:in `run'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/application.rb:270:in `block in fork_chef_client'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/application.rb:258:in `fork'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/application.rb:258:in `fork_chef_client'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/application.rb:224:in `block in run_chef_client'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/local_mode.rb:44:in `with_server_connectivity'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/application.rb:212:in `run_chef_client'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/application/client.rb:408:in `block in interval_run_chef_client'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/application/client.rb:398:in `loop'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/application/client.rb:398:in `interval_run_chef_client'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/application/client.rb:388:in `run_application'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/application.rb:60:in `run'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/bin/chef-client:26:in `<top (required)>'
/usr/bin/chef-client:54:in `load'
/usr/bin/chef-client:54:in `<main>'
```

**Comment by tyler-ball** [comment]
@lfrodrigues thats because this fix hasn't been released yet - it'll go out in the next version of chef-provisioning or you can use bundler to install from master

**Comment by lfrodrigues** [comment]
Sorry by bad, should have checked the date of last release...
