### ISSUE TITLE
Metachef weirdness

### ISSUE THREAD

**Issue by moos3** [chef/chef-provisioning-aws#499]
I am getting this error when I use chef-provisioning-aws with the mongodb3 cookbook. It only happens when I use the two together. If I use mongodb3 by itself no issues at all. Ideas?

```
==> default: Installing Cookbook Gems:
==> default: Compiling Cookbooks...
==> default:
==> default:
==> default: ================================================================================
==> default: Recipe Compile Error in /var/chef/cache/cookbooks/metachef/attributes/default.rb
==> default: ================================================================================
==> default:
==> default:
==> default: TypeError
==> default: ---------
==> default: no implicit conversion of String into Integer
==> default:
==> default:
==> default: Cookbook Trace:
==> default: ---------------
==> default:   /var/chef/cache/cookbooks/metachef/attributes/default.rb:9:in `[]'
==> default:
==> default:   /var/chef/cache/cookbooks/metachef/attributes/default.rb:9:in `from_file'
==> default:
==> default:
==> default: Relevant File Content:
==> default: ----------------------
==> default: /var/chef/cache/cookbooks/metachef/attributes/default.rb:
==> default:
==> default:
==> default:
==> default:   2:  default[:metachef][:conf_dir] = '/etc/metachef'
==> default:
==> default:   3:  default[:metachef][:log_dir]  = '/var/log/metachef'
==> default:   4:  default[:metachef][:home_dir] = '/etc/metachef'
==> default:
==> default:   5:
==> default:
==> default:   6:  default[:metachef][:user]     = 'root'
==> default:   7:
==> default:
==> default:   8:  # Request user account properties here.
==> default:   9>> default[:users]['root'][:primary_group] = value_for_platform(
==> default:
==> default:  10:    "openbsd"   => { "default" => "wheel" },
==> default:  11:    "freebsd"   => { "default" => "wheel" },
==> default:
==> default:  12:    "mac_os_x"  => { "default" => "wheel" },
==> default:
==> default:  13:    "default"   => "root"
==> default:  14:  )
==> default:
==> default:  15:
==> default:  16:  default[:announces] ||= Mash.new
==> default:
==> default:  17:
==> default:  18:  default[:discovers] ||= Mash.new
==> default:
==> default:
==> default:
==> default: Platform:
==> default: ---------
==> default: x86_64-linux
==> default:
==> default:
==> default:
==> default: Running handlers:
==> default: [2016-08-26T15:02:59+00:00] ERROR: Running exception handlers
==> default: Running handlers complete
==> default:
==> default: [2016-08-26T15:02:59+00:00] ERROR: Exception handlers complete
==> default: Chef Client failed. 0 resources updated in 26 seconds
==> default: [2016-08-26T15:02:59+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
==> default: [2016-08-26T15:02:59+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
==> default: [2016-08-26T15:02:59+00:00] ERROR: no implicit conversion of String into Integer
==> default: [2016-08-26T15:02:59+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

**Comment by nukepuppy** [comment]
is metachef actually working? its 4+ years old

**Comment by cgunasree08** [comment]
This issue or pull request is being automatically closed because the repository is being archived as part of the [Repository Standardization Initiative](https://github.com/chef-boneyard/oss-repo-standardization-2025).
